### PR TITLE
Add a requirements.txt to enable the running of this repo on mybinder.org

### PR DESCRIPTION
**Pull request by rdhyee**
When I read the following message in [ipywidgets/Using Interact.ipynb at ipython/ipywidgets](https://github.com/ipython/ipywidgets/blob/1c550518168311840ba8c810395598af85f51c58/examples/notebooks/Using%20Interact.ipynb)

> As of Jupyter 4.0, the widgets in this notebook won't show up on http://nbviewer.ipython.org. To view the widgets and interact with them, you will need to download this notebook and run it with a Jupyter Notebook server.

I turned to [binder](http://mybinder.org/) to run these widgets on a public server. To do so, I add a [requirements.txt at master](https://github.com/rdhyee/ipywidgets/blob/master/requirements.txt) listing `ipywidgets`.  One can launch my fork `rdhyee/ipywidgets` with [Binder](http://mybinder.org/repo/rdhyee/ipywidgets).

Merging this PR will make this main repo easy to run on mybinder.org.  (Although we might need to explain the purpose of `requirements.txt` here.)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@rdhyee thanks, binder is really awesome, but I don't think we can do this here:

- requiring `ipywidgets` from a `requirements.txt` file will get the ipywidgets version from pypi, while the notebooks in the repository in the master branch assume the current development version
- Another possibility would be to require `git+https://github.com/ipython/ipywidgets.git`in the `requirement.txt`, but then we should probably update the binder every time something gets merged into master for the binder to actually correspond to the repo.
- Binder is very well suited for repositories containing a few scripts and notebooks, requiring other libraries but for in the case of a larger project like ipywidgets, the ideal would be to have the base directory of the binder be a subdirectory of the project, which is not allowed by binder as of now.
- Another issue with having a `requiremenst.txt` in the base directory of the project is that it can be confused as the `setup.py`'s requirements.txt.

**Comment by rdhyee** [comment]
Thanks, @SylvainCorlay, for responding to my PR. I figured that what I did with my own repo is not suitable for general us -- but I did want to let the devs like you know about what I did to make the examples notebooks work on binder.

**Comment by SylvainCorlay** [comment]
Leaving it open so that @jdfreder may comment. I think it would require to use `git+https://github.com/ipython/ipywidgets.git` in your `requirements.txt`.

**Comment by rdhyee** [comment]
@SylvainCorlay Thanks for pointing out that I should be using `git+https://github.com/ipython/ipywidgets.git` -- I made the change in my repo

**Comment by SylvainCorlay** [comment]
Cool. FYI, you will probably need to re-generate your binder for this to be taken into account.

**Comment by rdhyee** [comment]
Yes, I regenerated the binder.  Don't think the `-e` was needed.

**Comment by jdfreder** [comment]
Are either of you familiar enough with the mechanics of Github and binder to know if the binder update could be triggered on merge?

**Comment by rdhyee** [comment]
Re: https://github.com/ipython/ipywidgets/pull/257#issuecomment-160503842 -- I don't know the answer but posed [a question at the binder repo](https://github.com/binder-project/binder/issues/41#issue-119517448).

**Comment by jdfreder** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
@rdhyee it seems that binder accepts subdirectories. Hence you could change the link of your badge to `http://mybinder.org/repo/rdhyee/ipywidgets/examples/notebooks` which solves one of the issues.

**Comment by SylvainCorlay** [comment]
btw, we prefer rebasing PRs on master rather than having merge commits in PRs.

**Comment by rdhyee** [comment]
@SylvainCorlay Sorry for not doing a rebase instead of merge.  Let me take care of that soon.

**Comment by Carreau** [comment]
Tagging as `closed-PR`, and closing as this is seem to have stalled a bit. 
This is just to keep the PR queue a bit shorter and focusing on what is actually worked on.
Feel free to reopen, (or ask for reopening if you don't have enough right to do so). 
If you were not the original author, and want to revive this, please feel free to do so. 

Also, we are doing our best to enable people to learn how to contribute to the project, and get commits in. If you are missing time or have any other issues that prevent you to work on that, please feel free to tell us, we can try to build on top of what you did. 

Thanks a lot and looking forward to see this moving forward again.

**Pull request closed without merging**
