### PR TITLE
Clear widget areas when output is cleared

### LINKED ISSUE #637: Clear widgets when a cell's output is cleared in classic notebook
Since clear output doesn't clear widgets, we need a clear widgets action in the Widget menu.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #637.

### CODE REVIEW

**Comment by jasongrout** [comment]
This needs jupyter/notebook#2173 in order to properly clear output areas.

**Comment by jasongrout** [comment]
Rebased for the new event name (see #2173)

**Comment by marscher** [comment]
Just a stupid question, why is the widget not removed when we call close on the backend side? I seems like there are some left overs after closing (namely an empty div element in the dom).

**Comment by jasongrout** [comment]
Great question. We discussed this also in https://github.com/jupyter-widgets/ipywidgets/issues/1845 -- basically it's a limitation of the notebook. However, I think https://github.com/jupyter-widgets/ipywidgets/issues/1845#issuecomment-350482904 points out a way we can get visually what we want without messing up the notebook.

Let's take the discussion to that issue so it's all in one place.

**Comment by marscher** [comment]
Thanks for the references and quick response!

**Pull request merged**
