### PR TITLE
Add datafiles for jupyterlab_widgets wheel

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by jasongrout** [comment]
This means that it's no longer necessary to do the labextension install step, at least if you want to install to sys-prefix, right?

**Comment by SylvainCorlay** [comment]
That is right. Although it remains necessary for dev install.

**Comment by minrk** [comment]
Nice!

**Comment by minrk** [comment]
Nice! This can put things in the wrong place for `--user` installs, but the consequences aren't dire.

**Comment by SylvainCorlay** [comment]
`--user`  is   👿

**Pull request merged**
