### PR TITLE
Use README.rst in manifest

### PR DESCRIPTION
**Pull request by jdfreder**

### CODE REVIEW

**Comment by minrk** [comment]
Wait, why are there two READMEs now?

**Comment by minrk** [comment]
I'm pretty sure this isn't the right thing to do - MANIFEST determines what files are included in a source release, which shouldn't exclude the README. I presume only one of README.md or README.rst should exist at all.

**Comment by SylvainCorlay** [comment]
@minrk we remove the rst and included a long description in setup.py.

**Comment by jasongrout** [comment]
See #132, where we did what Sylvain says.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
