### PR TITLE
Create single entry point for jupyter-js-widgets

### LINKED ISSUE #317: Single load point for jupyter-js-widgets in requirejs
Currently, custom widget libraries like bqplot import their dependencies from ipywidgets separately by requiring

`nbextensions/widgets/widgets/js/utils`
`nbextensions/widgets/widgets/js/widgets`

etc.
 
It would probably be much easier to ensure a smooth transition to npm packages if a single entry point for `jupyter-js-widgets` corresponding to npm's index.js was accessible under the static directory.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #317 . @jdfreder

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
We could also name this `index.js` like in node.

**Comment by jdfreder** [comment]
index.js would be better imho

**Comment by SylvainCorlay** [comment]
@jdfreder done. I also added a requirejs map to load "jupyter-js-widgets" by name.

**Comment by jdfreder** [comment]
:+1:

**Pull request merged**
