### PR TITLE
Make set_state and get_state symmetrical

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This is meant to solve #47.

### CODE REVIEW

**Comment by jdfreder** [comment]
With this PR I still can't `widget.set_state(widget.get_state())` right?  Instead I have to `widget.set_state(*widget.get_state())`.

**Comment by SylvainCorlay** [comment]
That is right.

**Comment by SylvainCorlay** [comment]
Well, it is back-backward-compatible.

**Comment by jdfreder** [comment]
This is great, thanks @SylvainCorlay !

**Pull request merged**
