### PR TITLE
Chain promises during comm_open handling

### LINKED ISSUE #561: ipywidgets 5.0 breaks AMD/require.js
Offshoot from https://github.com/jupyter-incubator/dashboards_server/issues/194.

If building *jupyter-js-widgets* as an AMD module to be used by require.js, loading of widgets is broken. See issue referenced above for history. Basically, [this change](https://github.com/ipython/ipywidgets/commit/fa33fc14b3b0b119e0a8e4d7c5aa72806cf226c3) in utils.js seems to introduce a timing issue, such that loading modules aren't handled at the correct time and model changes aren't correctly handled.

I [rewrote the web3 example](https://github.com/jhpedemonte/ipywidgets/tree/web3-requirejs) to build *jupyter-js-widgets* as an AMD module. When reloading the page, the widgets fail to render roughly 50% of the time. Compare to web3 on master, where they render 100% of the time.

I spent some time debugging https://github.com/jupyter-incubator/dashboards_server/issues/194 but was not able to find out where the timing issue lay.

cc @SylvainCorlay @parente

### PR DESCRIPTION
**Pull request by jhpedemonte**
Fixes #561

### CODE REVIEW

**Comment by jhpedemonte** [comment]
Other part of fix: https://github.com/jupyter/jupyter-js-services/pull/144

**Comment by SylvainCorlay** [comment]
✨ awesome!

**Comment by SylvainCorlay** [comment]
Can you please update the required version of jupyter-js-services to the one that includes your patch (0.10.2) in the examples where it is required?

**Comment by SylvainCorlay** [comment]
Nevermind, merging!

**Comment by SylvainCorlay** [comment]
backported

**Pull request merged**
