### PR TITLE
fixing setup.py for widgetsnbextension

### PR DESCRIPTION
**Pull request by ssunkara1**
This is needed for installing in windows

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
There is another instance of `check_call` in setup.py. Don't we need to make the same change there too?

**Comment by ssunkara1** [comment]
@SylvainCorlay I changed that too. I removed a function which seemed to be not doing much. Have a look.

**Comment by SylvainCorlay** [comment]
Thanks

**Comment by SylvainCorlay** [comment]
This looks good to me. I will wait a little bit to let @jasongrout comment.

@ssunkara1 when this gets in, would you be OK to contribute the same change in the cookiecutter ?

**Comment by ssunkara1** [comment]
@SylvainCorlay sure. I will do that.

**Comment by jasongrout** [comment]
This looks good to me too.

**Pull request merged**
