### PR TITLE
Remove support for old version

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@jdfreder

### CODE REVIEW

**Comment by blink1073** [comment]
Break :allthethings:

**Comment by SylvainCorlay** [comment]
@blink1073 what do you mean?

**Comment by blink1073** [comment]
I was kidding, Frenchie. 



—

**Comment by jdfreder** [comment]
@SylvainCorlay in retrospect, I'm not sure why I added the backwards compatibility.  Should I just merge this for 4.0?

**Comment by SylvainCorlay** [comment]
I like the idea of having a clean starting state for the post split.

**Comment by jdfreder** [comment]
Thanks

**Pull request merged**
