### PR TITLE
Support later version of jupyter-js-services

### PR DESCRIPTION
**Pull request by jhpedemonte**
In particular, update to pass along full message object in shim.

Tested by running `npm run test` in `ipywidgets/ipywidgets`.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@jhpedemonte did you test the web3 example?

**Comment by jdfreder** [comment]
The code looks good-

**Comment by jdfreder** [comment]
I'm having trouble running web3 with this PR, I'm unsure what's causing it, looking into it now.

**Comment by jdfreder** [comment]
I think this may be a bug in this newer version of jupyter-js-services...

**Comment by jdfreder** [comment]
@jhpedemonte please review https://github.com/jhpedemonte/ipywidgets/pull/1 which contains a fix for the changed jupyter-js-services API

**Comment by jdfreder** [comment]
Thanks!

**Pull request merged**
