### PR TITLE
Fix styling of slider (alignment with other widgets)

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Make the `IntSlider`and `FloatProgress` have width `@widget-width`. Now the `width`attribute of Dropdown controls the complete width.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@jdfreder A notebook to test alignment: https://gist.github.com/SylvainCorlay/5d4632fe274840222827

**Comment by SylvainCorlay** [comment]
The next fix should be base line fixes in the `[Float/Int]Progress`.

**Comment by jdfreder** [comment]
I haven't had a chance to try the branch, but the code looks good.

**Comment by SylvainCorlay** [comment]
This is ready. Fixed the baseline issues in the progress bars.

**Comment by jdfreder** [comment]
Ok, I'll test it - it will be a few minutes - I need to boot another machine.

**Comment by SylvainCorlay** [comment]
:+1: of course one must build the css.

**Comment by jdfreder** [comment]
Ok, just tested, this looks fantastic!  Great work @SylvainCorlay !

**Comment by jdfreder** [comment]
... I think it would be a good idea to upload the alignment notebook somewhere - maybe in the examples folder?  Or in the tests folder?

**Comment by SylvainCorlay** [comment]
Yes, that is right. I should probably polish it first, and add some comments...

**Pull request merged**
