### PR TITLE
remove gulp, trigger js/css in setup.py

### PR DESCRIPTION
**Pull request by minrk**
rebase, finish #81

### CODE REVIEW

**Comment by jdfreder** [comment]
So the test failure I was seeing earlier with the missing CSS... Magically gone?  Must have been related to another bug.

**Comment by jdfreder** [comment]
Ah, must have been
#87 and #91 (and corresponding notebook PRs)

**Comment by minrk** [comment]
Yup, I think it didn't have anything to do with your PR, but the real error was getting hidden somewhere.

**Comment by SylvainCorlay** [comment]
The README should also be updated.

**Comment by jdfreder** [comment]
I'm a bit confused.  I don't know why this passed the tests without https://github.com/jupyter/notebook/pull/120 .  I don't see where `python -m ipywidgets.install` is being called, therefor it should work without https://github.com/jupyter/notebook/pull/120 because the static assets are unavailbable to the front-end.

**Pull request merged**
