### PR TITLE
requirejs -> window.require

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@jdfreder

### CODE REVIEW

**Comment by blink1073** [comment]
This tricks webpack into not bundling it?

**Comment by SylvainCorlay** [comment]
`requirejs` is not a function...

**Comment by blink1073** [comment]
It is added when you use require.js

**Comment by SylvainCorlay** [comment]
Yes, but it's an object...

**Comment by jdfreder** [comment]
Requirejs works as a function too

**Comment by SylvainCorlay** [comment]
Not when I load requirejs like this: https://github.com/SylvainCorlay/embed-bqplot/blob/master/index.html#L3.

**Comment by blink1073** [comment]
What I'm interested in is using window.System so we can swtich to SystemJS for webpack 1 and 2.0.

**Pull request merged**
