### PR TITLE
Use requirejs modules instead of registry

### PR DESCRIPTION
**Pull request by jdfreder**
@SylvainCorlay here is what we talked about yesterday.

closes #414

### CODE REVIEW

**Comment by jdfreder** [comment]
This has broken the tests legitimately because the test don't use requirejs

**Comment by blink1073** [comment]
noice

**Comment by jdfreder** [comment]
@blink1073 Goog led me to this: https://github.com/webpack/webpack/issues/1952  Looks like I'm retracing some of your steps :stuck_out_tongue:

**Comment by blink1073** [comment]
Good times.

**Comment by jdfreder** [comment]
Turns out the test have been broken for a long time and have been artificially passing because an npm install step is failing and not returning a code...

**Comment by jdfreder** [comment]
This is ready

**Comment by blink1073** [comment]
:+1:

**Pull request merged**
