### PR TITLE
Request state in new_widget to get default values from traitlets

### PR DESCRIPTION
**Pull request by SylvainCorlay**
*waiting for travis*

### CODE REVIEW

**Comment by jdfreder** [comment]
No such file or directory, requirements.txt.  huh?

**Comment by SylvainCorlay** [comment]
I think that it is a problem with the previous PR by @minrk.

**Comment by minrk** [comment]
Rebase? I'm guessing it's because requirements.txt is removed in master, but .travis.yml is used from the branch.

**Comment by SylvainCorlay** [comment]
Rebased

**Comment by jasongrout** [comment]
Looks good.

**Pull request merged**
