### PR TITLE
Simplify set_state

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@jasongrout there is no need for this function to create a Promise.

### CODE REVIEW

**Comment by jdfreder** [comment]
This is possible because of the changes you made in #48, right?  No unpacking logic happens here or in any of the subsequent function calls.

**Comment by SylvainCorlay** [comment]
Yes, possibly. I am not sure why there was ever a promise here :)

**Comment by jasongrout** [comment]
line 205 now doesn't need a return, then: https://github.com/ipython/ipywidgets/pull/63/files#diff-6b2b6bc22cc17b1c445538ce9510948fR205

**Comment by SylvainCorlay** [comment]
Indeed, 6 more characters removed.

**Comment by jasongrout** [comment]
This looks good to me now.

**Pull request merged**
