### PR TITLE
Update README

### LINKED ISSUE #297: Add badges for RTD docs to README
Update README to link to hosted docs.

@Carreau can you add me as an admin on RTD for this https://readthedocs.org/projects/ipywidgets/
Thanks :sunny:

### PR DESCRIPTION
**Pull request by willingc**
Closes #297 

Add badges for Google Group and Docs.

Add resource section at end of file with helpful links including a PDF of the ipywidgets docs.

### CODE REVIEW

**Comment by willingc** [comment]
@captainsafia If you have time, please review this PR. Thanks :D

**Comment by captainsafia** [comment]
Overall looks good, I'm a bit iffy about whether or not we should include links to the Jupyter Notebook demo if there is already an ipywidgets demo notebook in the repo or a link to the Jupyter documentation.

In my mind, the resources section under each repo should be discrete and pertain only to that repo.

**Comment by willingc** [comment]
@captainsafia First, I didn't realize that there was an "ipywidgets demo" notebook. Now I see it's the first link in the readme (yet it never occurred to me to click it). So I definitely want to add a link to it on the bottom resources section. Huge thanks for you pointing that out.

In general, I would agree with you on pertaining to only one repo. Yet, the name confusion ipython/jupyter still persists. I think anything that gives greater name recognition for ipywidgets and its part in the Project Jupyter ecosystem is a positive action at this point. Down the road, we may go back to the repo specific but for now there's a benefit.

I'll push some changes this afternoon and ping you :sunflower:

**Comment by willingc** [comment]
@captainsafia Thanks for the suggestions and the review. I rearranged the Resources section and I like it much better now :dancers: I will merge this once Travis goes green.

**Comment by captainsafia** [comment]
unnamed

**Comment by willingc** [comment]
@captainsafia I love the gifs that you find!

**Pull request merged**
