### PR TITLE
[WIP] Integrate declarative widget base classes

### LINKED ISSUE #556: Integrate declarative widget base components into ipywidgets and jupyter-js-widgets
Hi all,

I'd like to integrate the fundamentals of the declarative widget framework into this repository.  Before I open a PR, I think it makes sense to roughly map what should be moved over or not.  The following picture of my whiteboard illustrates my understanding of the relevant subset of folders in decl. widgets.  Green checkmarks mean some or all should be moved into ipywidgets, red crosses mean none should be moved.  Crosses and checkmarks only exist on leaf nodes.

declwidgets

Would love for some quick feedback before I get started, @lbustelo @parente @SylvainCorlay .

Thanks!
Jon

### PR DESCRIPTION
**Pull request by jdfreder**
This PR adopts code from https://github.com/jupyter-incubator/declarativewidgets in the ipywidgets repository.  Open to contributions.

@lbustelo @parente @SylvainCorlay @ellisonbg 

closes #556

### CODE REVIEW

**Comment by ellisonbg** [comment]
I was under the impression that ipywidgets was only going to be refactored
slightly to have base functionality needed for the declarative widgets to
function. But this PR looks like it has most of the declarative widget
stuff, including actual widgets.

I don't think ipywidgest should have any notion of declarative widgets. We
should provide base functionality such as model syncing, comms, views, etc
that can be used in different ways. The existing declarative widgets would
be one possible way of using those things, but that wouldn't be in
ipywidgets itself (or jupyter-js-widgets).

Here are the important questions at this point:

* How do the core abstractions in ipywidgets need to be modified to make
things like declarative widget easier?
* Are there very small pieces of core logic (not actual widget
implementations) that need to be moved from declarativewidgets over to
ipywidgets to accomplish this?
* How does all of this interplay with widgets becoming more unified with
regular output?

And then:

* What does it look like to refactor the declarativewidgets to use the
cleaned up code base?
* Should the declarativewidgets include any actual widget implementations
or just the infrastructure to build declarative widgest?

Cheers, Brian



On Tue, May 3, 2016 at 3:56 PM, Jonathan Frederic <notifications@github.com>
wrote:

> This PR adopts code from
> https://github.com/jupyter-incubator/declarativewidgets in the ipywidgets
> repository. Open to contributions.
>
> @lbustelo <https://github.com/lbustelo> @parente
> <https://github.com/parente> @SylvainCorlay
> <https://github.com/SylvainCorlay> @ellisonbg
> <https://github.com/ellisonbg>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ipython/ipywidgets/pull/559
> Commit Summary
>
>    - Import from https://github.com/jupyter-incubator/declarativewidgets
>
> File Changes
>
>    - *M* ipywidgets/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-0> (2)
>    - *A* ipywidgets/declarative/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-1> (3)
>    - *A* ipywidgets/declarative/util/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-2> (2)
>    - *A* ipywidgets/declarative/util/base_serializer_py2.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-3> (63)
>    - *A* ipywidgets/declarative/util/base_serializer_py3.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-4> (61)
>    - *A* ipywidgets/declarative/util/functions.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-5> (139)
>    - *A* ipywidgets/declarative/util/functions_py2.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-6> (38)
>    - *A* ipywidgets/declarative/util/functions_py3.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-7> (59)
>    - *A* ipywidgets/declarative/util/serializer.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-8> (90)
>    - *A* ipywidgets/declarative/util/serializer_registrar.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-9> (17)
>    - *A* ipywidgets/declarative/util/serializers.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-10> (136)
>    - *A* ipywidgets/declarative/util/tests/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-11> (2)
>    - *A* ipywidgets/declarative/util/tests/test_functions.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-12> (229)
>    - *A* ipywidgets/declarative/util/tests/test_functions_py3.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-13> (106)
>    - *A* ipywidgets/declarative/widgets/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-14> (8)
>    - *A* ipywidgets/declarative/widgets/tests/__init__.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-15> (2)
>    - *A* ipywidgets/declarative/widgets/tests/test_urth_widget.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-16> (25)
>    - *A* ipywidgets/declarative/widgets/tests/test_widget_channels.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-17> (88)
>    - *A* ipywidgets/declarative/widgets/urth_exception.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-18> (14)
>    - *A* ipywidgets/declarative/widgets/urth_widget.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-19> (73)
>    - *A* ipywidgets/declarative/widgets/widget_channels.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-20> (92)
>    - *A* ipywidgets/declarative/widgets/widget_dataframe.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-21> (51)
>    - *A* ipywidgets/declarative/widgets/widget_function.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-22> (67)
>    - *A* ipywidgets/declarative/widgets/widget_ipw_proxy.py
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-23> (52)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-24> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/dynamic-properties-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-25> (132)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/error-display-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-26> (51)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/execution-complete-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-27> (41)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/jupyter-kernel-observer.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-28> (62)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/jupyter-notebook-env.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-29> (43)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/jupyter-save-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-30> (42)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/jupyter-widget-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-31> (280)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/shared-styles.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-32> (13)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/test/jupyter-save-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-33> (106)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-behaviors/test/jupyter-widget-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-34> (226)
>    - *A* jupyter-js-widgets/elements/declaritive/urth-core-bind/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-35> (27)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-bind/dom-bind-behavior.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-36> (160)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-bind/test/urth-core-bind.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-37> (214)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-bind/urth-core-bind.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-38> (158)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-39> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/test/urth-core-channel-broker.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-40> (542)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/test/urth-core-channel.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-41> (625)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/urth-core-channel-broker.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-42> (410)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/urth-core-channel-item.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-43> (69)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/urth-core-channel-viewer.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-44> (132)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-channel/urth-core-channel.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-45> (433)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-dataframe/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-46> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-dataframe/urth-core-dataframe.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-47> (156)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-function/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-48> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-function/test/urth-core-function.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-49> (1079)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-function/urth-core-function.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-50> (472)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-import/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-51> (27)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-import/test/urth-core-import-broker.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-52> (181)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-import/test/urth-core-import.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-53> (234)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-import/urth-core-import-broker.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-54> (153)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-import/urth-core-import.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-55> (234)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-storage/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-56> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-storage/test/urth-core-storage.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-57> (203)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-storage/urth-core-storage.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-58> (165)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-watch/bower.json
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-59> (25)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-watch/test/urth-core-watch.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-60> (117)
>    - *A*
>    jupyter-js-widgets/elements/declaritive/urth-core-watch/urth-core-watch.html
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-61> (65)
>    - *A* jupyter-js-widgets/less/declarative-widgets.less
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-62> (67)
>    - *M* jupyter-js-widgets/less/widgets.less
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-63> (1)
>    - *A* jupyter-js-widgets/src/declarative-widget.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-64> (39)
>    - *M* jupyter-js-widgets/src/index.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-65> (1)
>    - *A* widgetsnbextension/examples/urth-core-bind.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-66> (442)
>    - *A* widgetsnbextension/examples/urth-core-channel.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-67> (514)
>    - *A* widgetsnbextension/examples/urth-core-dataframe.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-68> (369)
>    - *A* widgetsnbextension/examples/urth-core-function.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-69> (0)
>    - *A* widgetsnbextension/examples/urth-core-import.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-70> (0)
>    - *A* widgetsnbextension/examples/urth-core-watch.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-71> (0)
>    - *A* widgetsnbextension/src/declarative/init/init.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-72> (0)
>    - *A* widgetsnbextension/src/declarative/main.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-73> (0)
>    - *A* widgetsnbextension/test/functional/Walkthrough.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-74> (0)
>    - *A* widgetsnbextension/test/functional/urth-core-bind-specs.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-75> (0)
>    - *A* widgetsnbextension/test/functional/urth-core-bind.ipynb
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-76> (0)
>    - *A* widgetsnbextension/test/functional/urth-system-test-specs.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-77> (0)
>    - *A* widgetsnbextension/test/utils/boilerplate.js
>    <https://github.com/ipython/ipywidgets/pull/559/files#diff-78> (0)
>
> Patch Links:
>
>    - https://github.com/ipython/ipywidgets/pull/559.patch
>    - https://github.com/ipython/ipywidgets/pull/559.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/559>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
No, the base functionality required for declarative widgets already exists in ipywidgets.  

There's a piece missing from jupyter/notebook that could be added, which is the restful service for loading bower assets.  This service could be expanded to include npm assets too.

Also, the components I brought in are only the bare minimum base of declarative widgets (or at least this is what I intended, @lbustelo will have to correct me if I included anything that shouldn't be upstreamed), the urth-core-* components.  It was my intention to bring these bits in, the supporting code, and the functional/unit tests.  Any of the actual declarative widgets that the user can construct, i.e. urth-help and urth-viz-*, should remain in the declarative widgets repo.

**Comment by lbustelo** [comment]
The more I think about this, the more I like the idea of keeping thing a bit more separate. I would not put a dividing line between urth-core-* and urth-viz-* In order to make a split. I think these are both essential building blocks of declarativewidgets. 

I'll put some more thought here tomorrow when I get to work.

**Comment by ellisonbg** [comment]
I don't recall us ever discussing or deciding to bring significant parts of
the declarativewidgets into ipywidgets itself. I am supportive of the
declarativewidgets, but I don't think this is the right path to
incorporation into jupyter itself.

I am much more interested in the declarativewidgets helping ipywidgets to
become a small, well designed core, on-top of which different things (like
the declarativewidgets) can be done.

Also, I think there are core design questions we need to answer such as how
output and widgets are related before declarativewidgets can become more
official.



On Tue, May 3, 2016 at 6:03 PM, Gino Bustelo <notifications@github.com>
wrote:

> The more I think about this, the more I like the idea of keeping thing a
> bit more separate. I would not put a dividing line between urth-core-* and
> urth-viz-* In order to make a split. I think these are both essential
> building blocks of declarativewidgets.
>
> I'll put some more thought here tomorrow when I get to work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/559#issuecomment-216713280>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Would love to get a take on this from @SylvainCorlay @parente @lbustelo @fperez

**Comment by lbustelo** [comment]
This is a very high-level view of how we put together declarative-widgets. 
components

When you look at the picture, I agree with @ellisonbg that it makes more sense to treat declarativewidgets as another project that depends on ipywidgets and jupyter-js-widgets. Our `urth-core-*` elements are analogous to bqplot and others that build on top of ipywidgets.

Another good reason to keep the project more independent is that our support matrix is wider than what individual releases of ipywidgets support. For example, the current `0.5.x` release of declarativewidgets supports Jupyter 4.x and ipywidgets 4.x and 5.1.1+.

So what makes sense to roll into ipywidgets? I think we are still early and trying to figure out bullet 1 of the [roadmap](https://github.com/jupyter/roadmap#next-1). As a starting point, I can offer the following, although not all might be particular to ipywidgets.

##### Browser side

1. Browser initiated creation of WidgetModels without the need for WidgetViews. That works fine now, but ipywidgets should have some tests in place to make sure that nothing breaks this usecase. Currently we have our own subclass of WidgetModel to avoid some issues introduced by used of Promises and assumption that all widgets need to request state from the kernel counterpart.
2. Inter-extension dependencies. This is probably not an issue in ipywidgets, rather a bigger issue in Notebook, but there is really nothing to coordinate the loading of browser extensions that depend on one another. We end up doing require tricks like [this](https://github.com/jupyter-incubator/declarativewidgets/blob/0.5.2/nb-extension/js/main.js#L25) to get things configured.
3. WidgetManaget discovery. Currently the manager is offered as a class from the module but instantiated and hung off some global by the hosting tool (i.e. Notebook). This goes back to point 2 above... is there a better solution?

##### Kernel side

1. We have code under `urth.util.*` that deals with serialization and may be something that is better placed in an upstream project (not necessarily ipywidgets)


I'll add to the list as I think of more things....

**Comment by jdfreder** [comment]
> I don't recall us ever discussing or deciding to bring significant parts of
> the declarativewidgets into ipywidgets itself.

We originally had the discussion last month, at the dev meeting.  It's also a part of the road map https://github.com/jupyter/roadmap#next1-60 - `Integrate framework/foundation classes of the Declaritive Widget incubator directly into jupyter-js-widgets and ipywidgets.`.   

> When you look at the picture, I agree with @ellisonbg that it makes more sense to treat declarativewidgets as another project that depends on ipywidgets and jupyter-js-widgets. Our urth-core-* elements are analogous to bqplot and others that build on top of ipywidgets.

This is different than what we discussed, but I'm happy to move forward in this direction as it minimizes the complexity of ipywidgets.  Thanks for outlining a few bite sized pieces that can live upstream, that helps a lot!  Is this okay with @SylvainCorlay and @parente ?

Also, where do we want to have the discussion about where the bower restful service should live?

**Comment by parente** [comment]
@ellisonbg said:

> Would love to get a take on this from @SylvainCorlay @parente @lbustelo @fperez 

While @jdfreder, @SylvainCorlay, and I (and others) had two brief chats about how to proceed at the dev meeting, it was mostly setup for follow-ons conversations with @lbustelo afterward (which I think happened). That's why the roadmap started with "Decide where to draw the line between Web Components specific functionality and generic code that should live closer to ipywidgets / jupyter-js-widgets to prevent future breakage." I think that's being figured out here.

> Thanks for outlining a few bite sized pieces that can live upstream, that helps a lot! Is this okay with @SylvainCorlay and @parente ?

I'm perfectly fine with any approach you all think is appropriate. And I hope I didn't give the impression that I *want* to see lots of declarative widgets get pushed into ipywidgets. (I don't!)

**Comment by jdfreder** [comment]
> Declaritive

Whoops, declarative*.  I don't know why I keep making that typo, SMH

**Comment by lbustelo** [comment]
@jdfreder 

> Also, where do we want to have the discussion about where the bower restful service should live?

I'm adding that to the post above...

**Comment by fperez** [comment]
Mmh, it sounds like @lbustelo and @parente are in agreement that we move a bit more slowly here for now. I don't necessarily oppose the idea that over time the core could grow more of the dec-widgets functionality, if we end up learning that it's more or less universally needed.  But the "support matrix" argument above is a compelling one to start a bit slower.

I suggest going with @lbustelo's list above as a starting point, though I'm not sure the npm/installation part of the conversation should happen here separate from the bigger (but similar) discussion of how to package/deploy extensions in general.  Unless I'm really confused, that problem here is just a reflection of the bigger one, so we should solve the main one, I think.

**Comment by haobibo** [comment]
Hi @jdfreder and @lbustelo  , one year past since this PR is closed, is there any plan for the integration of `declarativewidgets` and `ipywidgets` now? 
I use `declarativewidgets` a lot in my projects until the recent upgrade of notebook from 4.x to 5.0 break some features of `declarativewidgets`. I want to know is there a future plan for the widgets related projects.

**Comment by lbustelo** [comment]
@haobibo I've been busy working on a different project that does not leave me with time to maintain declwidgets. We need someone to keep up with changes in ipywidgets and jupyter and make the necessary fixes.

**Pull request closed without merging**
