### PR TITLE
WIP Make text area the same height as enclosing div

### PR DESCRIPTION
**Pull request by jasongrout**
WIP fix for #1077

### CODE REVIEW

**Comment by jasongrout** [comment]
This still doesn't quite do it - it stretches the textarea to be however high the enclosing box is, so, for example, we get a longer textbox if we have
```python
from ipywidgets import *

s = Textarea(description='hi')
i = IntSlider(description='another')
HBox([s,VBox([i,i,i,i,i])])
```
However, the textbox looks about 5 rows high in this case:
```python
from ipywidgets import *

s = Textarea(description='hi')
i = IntSlider(description='another')
HBox([VBox([s,i]),VBox([i,i,i,i,i])])
```
though in that case, the slider under the textarea doesn't align with the slider next to it.

Perhaps we give up on having integral-row textboxes, and just set the size to be about 3 widgets high (with inter-spacing). Another problem is that the widget and the textarea seem to be offset by one pixel when the align is baseline and the line-height is normal. Perhaps we need to set a lineheight to know for sure how much padding so that the top of the textbox is aligned with the top of the label and the baselines are also aligned.

@cameronoelson, thoughts about sizing the textarea compared to the other controls?

**Comment by jasongrout** [comment]
I reset the line-height to normal, since it was inheriting some 20px line height from somewhere in the notebook css. I think a line height of 28px as in most of the widgets is way to spread out for lines in a text box.

**Comment by SylvainCorlay** [comment]
Is this still WIP?

**Comment by jasongrout** [comment]
Yes. I'll work on this today.

**Comment by SylvainCorlay** [comment]
This was fixed in #1113

**Pull request closed without merging**
