### PR TITLE
interact - continuous update

### PR DESCRIPTION
**Pull request by denfromufa**
from gitter chat: https://gitter.im/ipython/ipywidgets

### CODE REVIEW

**Comment by jdfreder** [comment]
Awesome, thanks!

**Comment by SylvainCorlay** [comment]
It would be nice to strip the output of notebooks before committing it.

**Comment by denfromufa** [comment]
Why output should be removed? Do you having testing for these notebooks?

**Comment by SylvainCorlay** [comment]
Output it adds a lot of noise on git since it may change from execution to execution.

**Comment by jdfreder** [comment]
@SylvainCorlay it's okay, I'm going to add a PR that will add a few more things to these docs, I'll strip the output there.

**Comment by denfromufa** [comment]
OK, I'm adding the nested example as well. Continuous update as a second
button with True and False options.

**Comment by SylvainCorlay** [comment]
@denfromufa @jdfreder thanks!

**Pull request merged**
