### PR TITLE
Add all widget outputs to custom widget example

### PR DESCRIPTION
**Pull request by jdfreder**
@SylvainCorlay unfortunately I have to have all of the outputs for it to not run.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
What do you mean by "for it to not run"?

**Comment by jdfreder** [comment]
I mean to prevent nbsphinx from trying to run the notebook which requires extra dependencies on RTD that we don't need.  I opened a PR against nbsphinx adding a flag to disable this, but it hasn't been merged yet.  https://github.com/spatialaudio/nbsphinx/pull/39

**Comment by mgeier** [comment]
@jdfreder Just to clarify: you don't need to have all outputs, one output is enough for `nbsphinx` not to execute the notebook. In #506, however, you added only an `execution_count` and not an output.

Probably I should check for those, too?

I'll take care of your PR momentarily.

**Comment by jdfreder** [comment]
@mgeier I definitely executed the cell, it may be that the cell didn't result in any displayed output.  You probably want to correct your auto execute logic to account for that.  Jupyter widgets are also not output, so executing a cell with widgets only will probably cause failure in the auto execute logic too.

**Comment by mgeier** [comment]
OK, I'll extend the auto execute logic, see #41.

> Jupyter widgets are also not output

What are they then?
How do they look like in the representation provided by `nbformat`?

**Comment by mgeier** [comment]
@jdfreder FYI, I've extended the auto-execute logic in `nbsphinx` master.

**Pull request merged**
