### PR TITLE
SelectionSlider bugfix

### PR DESCRIPTION
**Pull request by afshin**
This bugfix resolves https://github.com/ipython/ipywidgets/issues/467

cc: @SylvainCorlay @jdfreder @jasongrout

### CODE REVIEW

**Comment by jasongrout** [comment]
We merged the 6.x branch into master. I confirmed that this PR does fix the issue in master.

@SylvainCorlay says he also fixed this issue in 5.x, and so this probably should have not been a problem since we merged master into the 6.x branch. He's going to look into the fix that was in 5.x and why it didn't make it into the master->6.x merge.

**Comment by SylvainCorlay** [comment]
Yeah, it seems that the 6.x branch reverted my fix.

**Comment by jasongrout** [comment]
@SylvainCorlay and I are going to go through my merge PR and check to see if anything else was reverted in the merge.

**Comment by afshin** [comment]
@jasongrout @SylvainCorlay Great, thanks for keeping me posted. If there's anything I should look at, please let me know.

**Comment by SylvainCorlay** [comment]
This one is opened on 6.x and seems to be fixed in master.

Closing.

**Comment by jasongrout** [comment]
This does *not* seem to be fixed in master for me.

**Pull request closed without merging**
