### PR TITLE
Add scrollable dropdown

### LINKED ISSUE #227: Scrolling dropdown.
Suggested by @stefanv in https://github.com/ipython/ipython/issues/8278

Why not switch to a scrollable dropdown when the list reaches a certain length? This is the same pattern followed elsewhere (e.g., output handling).

cc @olgabot

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #227, #94 (maybe).

This is hacky in some places, namely when used as an interaction it checks that the length of the items you wish to make an iteraction out of is larger than 10 and generates a scrollable dropdown in that case. It's a rather arbitrary number but I wasn't exactly sure how to select that number.

In general, I'll have to look at how this functions as an interaction some more but figured this is at least good for folks to take a look at.

cc: @jdfreder @ellisonbg

### CODE REVIEW

**Comment by jdfreder** [comment]
Can you justify why you implemented this as a separate widget instead of making the existing dropdown scrollable w/ a max height?

**Comment by captainsafia** [comment]
Now that I think about it, I really had no good reason to do all that, @jdfreder. I'll update it to just be CSS-based.

Gave me a good intro to ipywidgets though. :dancer:

**Comment by captainsafia** [comment]
OK. Updated.

Blegh, made some edits using Atom instead of Vim and Atom ended up fixing a ton of the whitespace. Let me know if that's gonna be a problem.

**Comment by jdfreder** [comment]
No, it's not a problem here.  The others get cranky when that happens in ipython/ipython and jupyter/notebook, which is why I keep my whitespace package disabled.  I think it's for good reason too, so the diffs aren't cluttered with whitespace changes.

**Comment by jdfreder** [comment]
I notice you still have this marked as WIP, however, the scrolling part of the PR appears to work:

working

I did notice the off the screen part of the PR does not work:

notworking

If you want, we can merge this as-is and you can work on the off the screen stuff in a separate PR.  What do you think?

**Comment by captainsafia** [comment]
That sounds reasonable. Feel free to merge.

**Comment by jdfreder** [comment]
Thanks @captainsafia :cake: !

**Pull request merged**
