### PR TITLE
update widget styling notebook

### LINKED ISSUE #715: Make modifying layout easier
Currently it's not very convenient to change something in a widget layout, especially if you need to change several properties, for example:

``` python
w = Button()
w.layout.width = '100px'
w.layout.height = '50px'
```

It could look much better:

``` python
w = Button().with_layout(width='100px', height='50px')
```

Personally I now use dumb monkey-patching for this:

``` python
def _with_layout(self, **kwargs):
    for k, v in kwargs.items():
        setattr(self.layout, k, v)
    return self

iw.DOMWidget.with_layout = _with_layout
```

and would really like to see something like this in `ipywidgets`!

### PR DESCRIPTION
**Pull request by ivanov**
This closes #715. I've fixed some typos, made each section's code
self-contained (no more `... import *`) and made other minor formatting
changes.)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@ivanov if you rebase on master, execute all and "save with widget state" from the widget menu, you will keep the serialized widget state in the notebook for the new rendering in the docs.

**Comment by jasongrout** [comment]
Also, #965 might simplify some of the examples.

**Comment by SylvainCorlay** [comment]
> Also, #965 might simplify some of the examples.

Wrong number!

**Comment by jasongrout** [comment]
> Wrong number!

I fixed it!

**Comment by SylvainCorlay** [comment]
> I fixed it!

Can you hop on gitter?

**Comment by SylvainCorlay** [comment]
Hum I don't think should have been merged as is.

**Comment by SylvainCorlay** [comment]
Cf comment above.

**Pull request merged**
