### PR TITLE
only filter stored snapshots

### LINKED ISSUE #554: All output_area elements are getting rerender on a notebook save
We noticed this recently and seems to be due to https://github.com/ipython/ipywidgets/blob/3a06dc11311e4d290227d9270729b15c3824b2ca/widgetsnbextension/src/manager.js#L592. This function executes on each notebook `save` and does not seem to filter which `output_area` to redisplay.

It is causing [this](https://github.com/jupyter-incubator/declarativewidgets/issues/339) issue in declarativewidgets.

/cc @SylvainCorlay @parente

### PR DESCRIPTION
**Pull request by minrk**
don't re-render outputs on the page

This should fix the problem of js outputs being re-executed on save.

I was a bit surprised that I didn't have to remove the snapshots from the page, but I don't seem to, because they don't seem to be there when this is called.

cc @SylvainCorlay and @jdfreder for review, in case there's something else needed here.

closes #554

### CODE REVIEW

**Comment by jdfreder** [comment]
I'm a little worried that this is a race condition, in that if ipywidgets gets loaded later the outputs will be on the page.  I'll take a look though.  Thanks for the PR!

**Comment by jdfreder** [comment]
@minrk this does not remove the widget snapshots for me, because the widget JS is loaded after the notebook contents have already rendered on the page.

Here's a gif illustrating the order of events:
noclear

I'll take a look at this now, expect a PR to your PR soon...

**Comment by jdfreder** [comment]
https://github.com/minrk/ipywidgets/pull/3 :smile:

**Comment by minrk** [comment]
Thanks for the extra fix, @jdfreder!

**Comment by SylvainCorlay** [comment]
LGTM.

**Comment by SylvainCorlay** [comment]
backported

**Pull request merged**
