### PR TITLE
Make HBox and VBox use classes instead of explicitly setting the styles.

### PR DESCRIPTION
**Pull request by jasongrout**
We run into problems when we set the element style of phosphor widgets - phosphor hides widgets by adding a css class, so if we set the display style of an element explicitly, it overrides phosphor hiding the element. This means that the element behaves badly in tabs, etc.

### CODE REVIEW

**Comment by jasongrout** [comment]
Another more far-reaching change is to disallow setting display in the Layout widget. Thoughts, @SylvainCorlay? It seems that people mainly use the Layout.display attribute to hide or show a widget - perhaps we should make a new widget that does that (with css), and deprecate the Layout.display attribute? You'd use this new widget like:

```python
h = Hideable(my_widget)
h.visible = True
h.visible = False
```

**Comment by jasongrout** [comment]
Or we could make Layout special-case the display attribute and use phosphor to hide the widget. That way it would work for every widget without having to wrap it.

**Comment by SylvainCorlay** [comment]
:+1: on all the changes of the PR as of now.

Unsure about the layout attribute question since layout systematically exposes all css properties that impact layout...

**Comment by jasongrout** [comment]
I would say that it's not a usual usecase to need the full power of the display attribute - usually you just want to set it to none or the default, where the default should be determined by the view on the javascript side and/or css. Accordingly, I think it would be fine to treat it special - display is true or false. 

In fact, I don't think it would be terrible to combine both display and visible to a tri-state attribute for display, hide, or collapse - that's often a point of confusion, the difference between display and visible.

**Comment by jasongrout** [comment]
Essentially, the problem with the layout is that it takes precedence over css styling, and that can break things like phosphor hiding a widget.

**Comment by SylvainCorlay** [comment]
In the examples such as flexbox based things, we also use `display: flex;`

**Comment by SylvainCorlay** [comment]
Happy to merge this one and carry on the discussion on `display`.

**Comment by SylvainCorlay** [comment]
We could make the `display` property an enum disallowing `hidden`. However, when the value differs from the default, it would prevent phosphor from hiding it...

**Comment by jasongrout** [comment]
> We could make the display property an enum disallowing hidden. However, when the value differs from the default, it would prevent phosphor from hiding it...

Yep, there's no way to win with exposing display, I think.

**Comment by jasongrout** [comment]
> In the examples such as flexbox based things, we also use display: flex;

The box widget now is basically a blank box with display: flex...

**Comment by ssunkara1** [comment]
@SylvainCorlay @jasongrout What was decided on this? So what is the right way to make a widget hidden?

**Comment by jasongrout** [comment]
Set `mywidget.layout.display = 'none'`, and to unhide `mywidget.layout.display=None` should work.

**Comment by jasongrout** [comment]
Or `mywidget.layout.display=''` should work too, and maybe be less confusing than `'none'` vs `None`.

**Pull request merged**
