### PR TITLE
Update examples for the 4.0 release

### LINKED ISSUE #114: Update widget example notebooks
Some of the example notebooks are outdated now.

### PR DESCRIPTION
**Pull request by jdfreder**
@jasongrout @SylvainCorlay 

closes #114

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This mostly reflects the new API to interact and link right?

**Comment by jdfreder** [comment]
Yes, and a couple bigsplit import changes.  I also uploaded some more images, removed some broken image links, and uploaded the low level widget talk from scipy.

**Comment by jasongrout** [comment]
This looks generally okay to me (I didn't look at everything in detail).

**Comment by SylvainCorlay** [comment]
Jason and I are running all the notebooks.

**Comment by SylvainCorlay** [comment]
The date picker' s up and down arrows in the examples are not quite aligned with the textbox.

**Comment by SylvainCorlay** [comment]
The "factoring" polynomial does not use MathJax

**Comment by jdfreder** [comment]
WRT the date time picker, that's a browser control IIRC.  It could be that some of the Bootstrap CSS is causing it to render strangely.

**Comment by SylvainCorlay** [comment]
ok

**Comment by jasongrout** [comment]
`def f(x:True):` in Using Interact

**Comment by jdfreder** [comment]
> def f(x:True): in Using Interact

@jasongrout , what about it?  It works for me- are you using Python 3?

**Comment by jasongrout** [comment]
oh, right.  It does say it's for python 3.  I'll add a comment too.

**Comment by jasongrout** [comment]
@jdfreder, I'm correcting a bunch of grammar in at least the Using Interacts notebook.

**Comment by SylvainCorlay** [comment]
@jasongrout open a different PR?

**Comment by jasongrout** [comment]
sure, I can, or put in a PR to your PR

**Comment by jdfreder** [comment]
Yeah @jasongrout if you could open a PR against this one, or open one after this one, whichever you prefer, that would be excellent !

**Comment by jasongrout** [comment]
Updates here: https://github.com/jasongrout/ipywidgets/tree/updateexamples (I'll open a PR when I'm done)

**Pull request merged**
