### PR TITLE
Allow html in labels

### LINKED ISSUE #817: Labels should allow HTML code?
Currently, the label (i.e. the `description` attribute) of a widget is displayed as plain text (with LaTeX support). It would be useful to allow arbitrary HTML.

---
## Summary
Should the description accept html? Right now it doesn't by design, but we could change that.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #817

### CODE REVIEW

**Comment by jasongrout** [comment]
This doesn't allow html in buttons - if we want to do that, let's make a different ticket?

**Comment by SylvainCorlay** [comment]
Html in buttons are a good way to give the opportunity to break layout and all. I am not sure this is a good idea.

**Comment by jasongrout** [comment]
> I am not sure this is a good idea.

html in labels, or buttons, or both?

**Comment by SylvainCorlay** [comment]
Buttons would be more dangerous than labels.

**Pull request merged**
