### PR TITLE
Add sensible default styling to the button.

### PR DESCRIPTION
**Pull request by jdfreder**
@ellisonbg here are the default styles we were talking about.

### CODE REVIEW

**Comment by jdfreder** [comment]
@SylvainCorlay this may have an impact on bqplot buttons for the same reason I've marked it as backwards incompat. and targeted 5.0.

**Comment by ellisonbg** [comment]
We are talking about this now - can you join Sylvain and I on
appear.in/jupyter

On Thu, Oct 29, 2015 at 11:35 AM, Jonathan Frederic <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> here are the default styles we
> were talking about.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ipython/ipywidgets/pull/204
> Commit Summary
>
>    - Add sensible default styling to the button.
>
> File Changes
>
>    - *M* ipywidgets/widgets/widget_button.py
>    <https://github.com/ipython/ipywidgets/pull/204/files#diff-0> (4)
>
> Patch Links:
>
>    - https://github.com/ipython/ipywidgets/pull/204.patch
>    - https://github.com/ipython/ipywidgets/pull/204.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/204>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
The widget.less does not have anything for button. It could be set to `@widget-width`.

**Comment by jdfreder** [comment]
> We are talking about this now - can you join Sylvain and I on
> appear.in/jupyter

yes

**Comment by jdfreder** [comment]
There are larger issues here, @SylvainCorlay has opened a big issue to describe them all.

**Pull request closed without merging**
