### PR TITLE
Set MultipleSelect initial value after setting it to be multiple select

### LINKED ISSUE #106: IPython SelectMultiple widget does not always reflect selected_labels
I have been working with the IPython SelectMultiple widget and it does not always correctly display the selected labels on the widget. The easiest way to reproduce this is to set selected_labels before displaying.

Minimal code to reproduce:
```
from ipywidgets import widgets
from IPython.display import display

sm = widgets.SelectMultiple(options=['a', 'b', 'c'], selected_labels=['a', 'b', 'c'])
display(sm)
print sm.value
print sm.selected_labels
```

Workaround, shows as expected:
```
sm2 = widgets.SelectMultiple(options=['a', 'b', 'c'])
display(sm2)
sm2.selected_labels = ['a', 'b', 'c']
print sm2.value
print sm2.selected_labels
```

Requested Version info:
```
python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'0b5f4a8',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/redacted_path/.local/lib/python2.7/site-packages/IPython',
 'ipython_version': '4.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-431.20.3.el6.x86_64-x86_64-with-redhat-6.5-Santiago',
 'sys_executable': '/redacted_path/anaconda/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

### PR DESCRIPTION
**Pull request by jasongrout**
Only one value is selected otherwise.

Fixes #106

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
The test failures are the ones of #56 . Restarting the tests.

**Comment by SylvainCorlay** [comment]
This seems related but only happened in one of the js test series (race condition?):

```
Test file: /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ipywidgets/tests/bin/tests/widget_selectioncontainer.js
FAIL Front-end JS error
#    type: fail
#    file: /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ipywidgets/tests/bin/tests/widget_selectioncontainer.js
#    subject: false
```

**Comment by SylvainCorlay** [comment]
Re-ran the tests and everything is green.

**Comment by jdfreder** [comment]
Tested, works, looks good!  Thanks @jasongrout

**Pull request merged**
