### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by jasongrout**
Supersedes #802, based on JupyterLab 0.7.0.

This adds accordion styling and tweaks a few other settings on top of the #802.

### CODE REVIEW

**Comment by jasongrout** [comment]
@SylvainCorlay - do you want to take a look at this and merge if it looks good, and we can iterate from here? @gnestor - feel free to take a look too!

**Comment by SylvainCorlay** [comment]
@jasongrout thanks this is great.  - and thanks for following the pattern of the earlier commits.

**Comment by SylvainCorlay** [comment]
Tested everything. Merging and opening other PRs to iterate.

**Comment by jasongrout** [comment]
Cool, thanks!

**Comment by SylvainCorlay** [comment]
In which timezone do you live?

**Comment by jasongrout** [comment]
Apparently I'm in Europe these days :)

**Comment by gnestor** [comment]
I finally got my jupyterlab_widgets working again and the widgets are all working properly and the styling looks great!

**Pull request merged**
