### PR TITLE
Fix config metadata to use .tag()

### PR DESCRIPTION
**Pull request by jasongrout**
This depends on ipython/traitlets#53.  It also includes https://github.com/ipython/ipywidgets/pull/95 to prevent merge conflicts in the future.

### CODE REVIEW

**Comment by jdfreder** [comment]
This should be done before ipywidgets 5.0 is released.

**Comment by SylvainCorlay** [comment]
Closing as per discussion in person with Jason.

**Comment by jdfreder** [comment]
Do you want me to open a new version of this?

**Comment by SylvainCorlay** [comment]
Yes, there is a PR coming this afternoon.

**Pull request closed without merging**
