### PR TITLE
Remove the Proxy and PlaceProxy widgets

### LINKED ISSUE #978: Update proxy widget to use Phosphor to attach children widgets
The proxy widget currently doesn't use the phosphor mechanism, so phosphor messages stop at the proxy widget boundary.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #978 (so the fix is in the history), and then removes the widgets. We don't feel there is a compelling usecase for Proxy (using a Box with a single child has much the same effect), and the PlaceProxy widget gets very tricky, especially when there are multiple copies of a notebook on a single page, as in JupyterLab.

### CODE REVIEW

**Comment by jasongrout** [comment]
@SylvainCorlay - do we actually use the proxy widget at all anymore? We don't use it internally except for the PlaceProxy widget, which we both think should be deleted. I'm inclined to delete the Proxy widget as well.

**Comment by SylvainCorlay** [comment]
Besides the place proxy, we used `Proxy` a lot to apply styles to the contained widget.

**Comment by jasongrout** [comment]
Yes, I think we should encourage people to use the Box with a single child in the cases where they need a placeholder with a specific layout.

**Comment by jasongrout** [comment]
(@SylvainCorlay and I discussed this, and agreed to merge this PR when I fixed the import issue that was causing tests to fail)

**Comment by SylvainCorlay** [comment]
Fyi. The proxy widget approach to styling allowed two views of the same widget to be styled differently when displayed in different context.

(One in a proxy, one e.g. in an output area).

This was useful for the figure builder which is a complex gui but not much otherwise.

**Comment by hainm** [comment]
@jasongrout I used to use PlaceProxy to put ipywidgets' GUI to `nglview` GUI in full screen mode.

The idea is to mimics this: http://arose.github.io/ngl/ but using Python (via ipywidgets) to write the GUI and add that to the existing Javascript code.

**Comment by hainm** [comment]
picture2

**Comment by maartenbreddels** [comment]
I'm also using my custom fullscreen code, maybe there needs to be support for fullscreen somewhere.

**Comment by SylvainCorlay** [comment]
> I'm also using my custom fullscreen code, maybe there needs to be support for fullscreen somewhere.

That would be context dependent (jupyterlab vs jupyter) so there might not be a clean way to have this in jupyter-js-widgets.

**Comment by maartenbreddels** [comment]
Why not, I mean, fullscreen is fullscreen, it shouldn't care about the rest.

**Comment by SylvainCorlay** [comment]
Right, I misread and thought this was full browser window.

**Comment by jasongrout** [comment]
Very nice, @hainm! We have a much more flexible system for rendering widgets now that widgets are normal displayed outputs - let's see if there is a way to use that to get what you want.

Is that full screen UI running in the the notebook, or in a custom webpage?

**Comment by hainm** [comment]
> Is that full screen UI running in the the notebook, or in a custom webpage?

it's running in the notebook. 

```python
import nglview
nglview.demo()
```

--> Then you can double-click to the widget to go to fullscreen mode.

My idea is that to build GUI controls by `ipywidgets`, then insert it to fullscreen mode.

**Pull request merged**
