### PR TITLE
Send resize message when the layout changes

### PR DESCRIPTION
**Pull request by jasongrout**
Also, change LayoutView to use the already-available parent option.

Fixes https://github.com/bloomberg/bqplot/pull/371#issuecomment-265224920

### CODE REVIEW

**Comment by jasongrout** [comment]
@ssunkara1 - can you verify that this fixes the bqplot issue?

**Comment by ssunkara1** [comment]
@jasongrout Sure will check this. Thanks

**Comment by jasongrout** [comment]
Also fixes #945

**Comment by SylvainCorlay** [comment]
Could we also remove the triggering of `displayed` for child widgets by the box widgets?

The phosphor machinery should propagate the attach events and DOMWidgets now triggers its own `displayed` event when attached.

**Comment by jasongrout** [comment]
@SylvainCorlay, The box widget already uses phosphor machinery: https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_box.ts#L299

The proxy widget needs to be fixed to use phosphor machinery, but let's make that a different PR.

**Comment by jasongrout** [comment]
> The proxy widget needs to be fixed to use phosphor machinery, but let's make that a different PR.

See #978 and #979.

**Comment by ssunkara1** [comment]
@jasongrout The change looks good for bqplot. The `resize` handlers are triggered once the `Layout` is applied. Thanks!

**Comment by SylvainCorlay** [comment]
I am inclined to merge. 

Although in the original #794, we were listening to the layout changes from the widget model (instead of the layout view), which allowed to stop listening to the old layout when a new value was assigned.

I am unsure that this implementation prevents a zombie layout view to trigger resize events when its model changes.

**Comment by SylvainCorlay** [comment]
^ @jasongrout

**Comment by jasongrout** [comment]
> Although in the original #794, we were listening to the layout changes from the widget model (instead of the layout view), which allowed to stop listening to the old layout when a new value was assigned.

That's much better, and means we don't have this weird logic to pass the parent into the child. I'll change this.

**Comment by jasongrout** [comment]
CC @SylvainCorlay, @ssunkara1

**Comment by jasongrout** [comment]
There are a lot of extra commits in here. Let me clean them out.

**Comment by jasongrout** [comment]
Okay, I think it's cleaned up now, and ready to test.

**Pull request merged**
