### PR TITLE
WIP UI to embed widgets in bare html pages.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This comes on the top of #423.

embed

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
A first prototype for the UI

**Comment by ellisonbg** [comment]
Lots to review, but this is amazing :-)

On Tue, Mar 15, 2016 at 9:52 PM, Sylvain Corlay <notifications@github.com>
wrote:

> A first prototype for the UI
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/424#issuecomment-197153302>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
@ellisonbg yeah we a few things to improve before this gets in. We are discussing a few items with @jdfreder such as
 - putting up cdns for jupyter-js-widgets, specify the required version of the cdn in the manager state and require the right one.
 - discuss other ideas for the inline representation for widget state than the current script tag.
 - remove a couple of unnecessary things in the serialized state.

**Comment by jdfreder** [comment]
Seems to me it would be beneficial if the state wasn't included at the document level and there was a cell toolbar so that users could get state for a particular cell.  That way they could embed the content where they want on their page.

**Comment by SylvainCorlay** [comment]
> Seems to me it would be beneficial if the state wasn't included at the document level and there was a cell toolbar so that users could get state for a particular cell. That way they could embed the content where they want on their page.

We probably can't do that because of interactions between widget models that are referencing each other, or may not be displayed in the same cell or displayed at all.

"displayed under cell [x]" is not a selection criterion we can use.

**Comment by SylvainCorlay** [comment]
> Seems to me it would be beneficial if the state wasn't included at the document level and there was a cell toolbar so that users could get state for a particular cell. That way they could embed the content where they want on their page.

The problem is that certain widgets are not bound to any cell. A solution would be to get *all* the model but only *render* the top-level widgets of interest (of a specific cell).

**Comment by fperez** [comment]
Very cool!! Just signing in for now to watch the discussion... Thanks for the pointer :)

**Comment by jdfreder** [comment]
Pulled into #426 per @SylvainCorlay 's request

**Comment by SylvainCorlay** [comment]
:+1: let's continue the work there as we iterate on the embedded widget manager.

**Pull request closed without merging**
