### PR TITLE
Yet another awesome test suite

### PR DESCRIPTION
**Pull request by jdfreder**
meme

### CODE REVIEW

**Comment by jdfreder** [comment]
I deprecate `on_some_change` in this PR as Backbone supports it intrinsically.

**Comment by jdfreder** [comment]
@SylvainCorlay this is ready for you to look at.  It includes tests for ManagerBase and WidgetModel.

It does not include
- round trip tests
- individual widget view tests
- widget view and dom view tests

**Comment by jdfreder** [comment]
Oh, I should have mentioned.  This uses Chrome and Firefox on Travis!  woot!

**Comment by SylvainCorlay** [comment]
Merging as discussed in person.

**Pull request merged**
