### PR TITLE
Convert dev_docs.rst to markdown

### PR DESCRIPTION
**Pull request by gnestor**
The link on `dev_install.md` was broken. This fixes it and makes its format consistent with the other docs that are written in markdown.

### CODE REVIEW

**Comment by gnestor** [comment]
@jasongrout Care to merge?

**Comment by jasongrout** [comment]
@gnestor - if you have time to look at the other PRs I've been submitting, I'd love another set of eyes on them.

**Comment by jasongrout** [comment]
Just one small comment, and I think this is good to merge.

**Comment by gnestor** [comment]
Updated! 👌

**Comment by SylvainCorlay** [comment]
👍

**Pull request merged**
