### PR TITLE
Add an on_change callback to Selection widgets

### PR DESCRIPTION
**Pull request by blink1073**
This is similar to the `on_submit` callback for `Text` widgets.

screen shot 2015-08-23 at 11 09 28 am

### CODE REVIEW

**Comment by jasongrout** [comment]
Can't you trigger the callback from the change in the value attribute?

```python
from ipywidgets import Dropdown
from IPython.display import display
def callback(trait, value):
    print("***changed", value)
dd = Dropdown(value='hello', options=['hello', 'goodbye'])
dd.on_trait_change(callback, 'value')
display(dd)
```

**Comment by blink1073** [comment]
I tried that, but I wanted a closure around the name of the variable being changed.  I used `functools.partial`, but it was interfering with the argspec logic of `on_trait_change`.  I tried all different numbers of arguments, but none would respect my closure.

**Comment by jasongrout** [comment]
https://github.com/ipython/traitlets/pull/43 gives you a reference to the HasTraits object that contains the Trait that is being changed.  Is that what you needed?  If so (after updating the most recent traitlets), make your callback take (name, old, new, obj) as arguments.

Or were you trying to have a closure for something else?

**Comment by blink1073** [comment]
I wanted a callback that had the name of the variable being edited by the `Dropdown`.  The object in the `on_traits_change` would be the `DropDown`, not my variable, no?

**Comment by blink1073** [comment]
Context: I was trying to set up an auto-editor for a `HasTraits` class.  For an Enum, I was creating a `Dropdown`, where a change in the value would propagate back to my `HasTraits` instance.

**Comment by jasongrout** [comment]
Like this?

```python

from ipywidgets import Dropdown
from IPython.display import display
from traitlets import HasTraits, Enum
class myclass(HasTraits):
    x = Enum(['hello', 'goodbye'], default_value='hello')
def make_gui(obj, attr, trait):
    def callback(name, new):
        print("**changed", attr, new)
    dd = Dropdown(value=getattr(obj, attr), options=trait.values)
    dd.on_trait_change(callback, 'value')
    return dd

def make_editor(obj):    
    for attr, trait in obj.traits().items():
        display(make_gui(obj, attr, trait))
```

**Comment by blink1073** [comment]
Since you asked, here's what I'm using:

```python

def edit_traits(obj):
    """Create an IPython widget editor for a Traits object"""
    names = sorted(obj.trait_names())
    names.remove('name')
    names = ['name'] + names
    items = [Text('', disabled=True)]
    for name in names:
        if name.startswith('_'):
            continue
        try:
            value = getattr(obj, name)
        except TraitError:
            value = None
        trait = obj.traits()[name]
        if (trait.get_metadata('readonly') or
                isinstance(trait, Instance) or value is None):
            items.append(Text(str(value), disabled=True))

        elif isinstance(trait, Enum):
            # create a closure around "name" for the on_trait_change
            # callback
            def create_dropdown(name):
                dd = Dropdown(value=value, options=trait.values)

                def callback(dummy, value):
                    setattr(obj, name, value)
                dd.on_trait_change(callback, 'value')
                items.append(dd)

            create_dropdown(name)
        else:
            def callback(name, textbox):
                try:
                    setattr(obj, name, textbox.value)
                except Exception:
                    textbox.color = 'red'

            text = Text(str(value))
            text.on_submit(functools.partial(callback, name))
            items.append(text)
    labels = [Text(name, disabled=True) for name in names]
    labels = [Text(obj.__class__.__name__, disabled=True)] + labels
    display(HBox(children=[VBox(children=labels), VBox(children=items)]))
```

**Comment by SylvainCorlay** [comment]
Do you still have interference with the argspec when using the new proposed API for traitlets?
https://github.com/ipython/traitlets/pull/61/

**Comment by blink1073** [comment]
@SylvainCorlay, good call, this works:

```python
def callback(tname, change):
                print(tname, change)
                
dd = Dropdown(value=value, options=trait.values)
dd.observe(partial(callback, name), 'value')
items.append(dd)
```

I guess the question is whether this PR is still a valid addition, providing symmetry with other widgets that have callbacks?

**Comment by SylvainCorlay** [comment]
Although we may still want to figure out where this other PR will go
because we also considered calling the `observe` method `on_change`...

Besides, the other non-traitlet-related callbacks in widgets are usually
meant to register to events that are not related to attribute state changes
and the PR on signaling is meant to address this. It deprecates `on_submit`.

Actually it also depends on the trailets PR because I need to know the
final decision for the signature of change handlers. (I have a state_change
signal in every widget)...

**Comment by blink1073** [comment]
Fair enough, closing this one.

**Pull request closed without merging**
