### PR TITLE
Play widget

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Adding a [Play/Pause/Stop] set of buttons triggering `setTimeout`-based iteration on integers.

This should make it easier to author animations like the "wealth of nations" recreation in bqplot https://github.com/bloomberg/bqplot/pull/152

Bellow, a use case which is a re-creation of the ever popular 'wealth of nations' demo, reproduced by @dmadeka with bqplot.

screencast-wof

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@jasongrout comments welcome!

**Comment by stonebig** [comment]
no rewind/fast-backward/fast-Forward ?

**Comment by SylvainCorlay** [comment]
Actually the screenshot is not accurate anymore. The styling of the `Play` widget is a bit nicer now (spacing between).

**Comment by SylvainCorlay** [comment]
Hum, no fast-forward, for now but you can set the value with a slider...

**Comment by SylvainCorlay** [comment]
Added a minimal documentation and updated the screencast.

**Comment by hainm** [comment]
Cool. Thanks.

**Comment by SylvainCorlay** [comment]
Backported.

**Pull request merged**
