### PR TITLE
Decouple

### LINKED ISSUE #13: Decouple the widgets from the Notebook.
Decoupling the widgets from the Notebook should make it easier for people to embed the widgets in their own non-notebook environment.  For example, @rgbkrk has already expressed interest in doing this with his BitJet widget and Sidecar app.

This means splitting the WidgetManager into a WidgetManager or WidgetManagerBase (depending on whether or not it can be used without being inherited) and a NotebookWidgetManager.

We also may want to think about the installation a little more carefully, which we will have to do soon anyways.  Users may want to install (A) for use with the notebook (B) for standalone use.  If @SylvainCorlay 's proposal for kernel resource/extensions is implemented, (A) is instead to a specific kernel, not the notebook.

### PR DESCRIPTION
**Pull request by jdfreder**
The PR does a lot.

- Break problematic coupling with the notebook
- Shim using *amdefine* when loading from a commonjs environment
- Beef up the npm package.json, making it the premiere way to deploy.  See the changes to RELEASE.md for details

I'm not doing anything backwards incompatible in this PR, because I want it to be released with 4.2.0.  When we are ready to work on 5.0, a lot of this code will clean up, because I will convert everything to commonjs and browserify.

closes #13

### CODE REVIEW

**Comment by jdfreder** [comment]
@rgbkrk this will be the last piece you need to get going.  I'll add an example project in the examples folder so you can see how to use this in an npm project.

**Comment by rgbkrk** [comment]
Well that's exciting. That means I can start sticking it in sidecar.

**Comment by ellisonbg** [comment]
Awesome. Can you say more about how you are using amddefine? Why not just tell people if they need to load this in a non AMD environment they can use System.js. What exactly does amddefine do?

**Comment by jdfreder** [comment]
I think system.js would work too, for the same reason amdefine works.  I'll give system.js a try, I'm not attached to amdefine at all, I just saw it on the require.js webpage as the recommended way to load AMD inside a commonjs env.  I have a couple goals:
1.  Don't change any of the files that are already AMD to CJS
2.  Create a node package package that can both be imported and used in CJS, and also bundled using a JS bundler.

**Comment by jdfreder** [comment]
I wasn't able to accomplish my second goal using systemjs because of https://github.com/systemjs/systemjs/issues/192 .  I'm still looking into a workaround.

**Comment by ellisonbg** [comment]
Can you ping @blink1073 on this. He has been working through a lot of the
details with system.js.

Also, at what stage are you using browserify. In my view, using System.js
removes the need to use browserify altogether. The problem with browserify
is that you can only reasonably do it a single time without running into
duplicate deps being loaded.

On Wed, Oct 21, 2015 at 11:45 AM, Jonathan Frederic <
notifications@github.com> wrote:

> I wasn't able to accomplish my second goal using systemjs because of
> systemjs/systemjs#192 <https://github.com/systemjs/systemjs/issues/192> .
> I'm still looking into a workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/193#issuecomment-149938763>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
> Can you ping @blink1073 on this. He has been working through a lot of the
> details with system.js.

You just did :)

**Comment by blink1073** [comment]
You rang?   Yes, I've been following along.  At some point we may have to declare that `steal.js` is the preferred way to load these complex mixed packages.

**Comment by jdfreder** [comment]
> Also, at what stage are you using browserify. In my view, using System.js
> removes the need to use browserify altogether. The problem with browserify
> is that you can only reasonably do it a single time without running into
> duplicate deps being loaded.

The end user should be able to browserify.

**Comment by jdfreder** [comment]
> You rang? Yes, I've been following along. At some point we may have to declare that steal.js is the preferred way to load these complex mixed packages.

Thanks- I'll give stealjs a try and ping back with the results.

**Comment by ellisonbg** [comment]
Can you clarify what amddefine does and how you are using it? Is it being
used by third parties to load your code, or by you yourself? Thanks for
clarifying though - I agree that users should be able to browserify
themselves if needed. Is amddefine just a stopgap until ipywidgets in
CommonJS itself?

On Wed, Oct 21, 2015 at 12:11 PM, Jonathan Frederic <
notifications@github.com> wrote:

> You rang? Yes, I've been following along. At some point we may have to
> declare that steal.js is the preferred way to load these complex mixed
> packages.
>
> Thanks- I'll give stealjs a try and ping back with the results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/193#issuecomment-149948079>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
> Can you clarify what amddefine does and how you are using it? Is it being
> used by third parties to load your code, or by you yourself? 

I'm trying to replace amdefine with steal.js now, I'll ping back when I have success or failure.

amdefine is a minimal layer allowing AMD define tags to be used in a CJS environment.  It also allowed me to replace the funky nbextensions import paths with actual paths.  amdefine was only being used inside ipywidgets, no one else would need to know of its existence.

> Is amddefine just a stopgap until ipywidgets in
> CommonJS itself?

Exactly

**Comment by ellisonbg** [comment]
OK, doesn't sound too bad if it is a stopgap them, I am just trying to
learn all the different ways these things fit together.

On Wed, Oct 21, 2015 at 12:28 PM, Jonathan Frederic <
notifications@github.com> wrote:

> Can you clarify what amddefine does and how you are using it? Is it being
> used by third parties to load your code, or by you yourself?
>
> I'm trying to replace amdefine with steal.js now, I'll ping back when I
> have success or failure.
>
> amdefine is a minimal layer allowing AMD define tags to be used in a CJS
> environment. It also allowed me to replace the funky nbextensions import
> paths with actual paths. amdefine was only being used inside ipywidgets, no
> one else would need to know of its existence.
>
> Is amddefine just a stopgap until ipywidgets in
> CommonJS itself?
>
> Exactly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/pull/193#issuecomment-149952504>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
I'd say what Jon has already done is fine, since this is transitional.  I believe our end goal is to write each library with one style (distributed as CJS), and then folks can use whatever they want to put pieces together, but `steal.js` seems to be the best way.

**Comment by jdfreder** [comment]
This is ready for review.  I've uploaded two examples, one on how to use ipywidgets from within node using `jsdom` and `navigator`, and one showing how to use it in the browser using `browserify`.

**Comment by jdfreder** [comment]
demo

**Comment by rgbkrk** [comment]
This is a great step forward!!!

**Comment by SylvainCorlay** [comment]
:+1: I could even use it with bqplot. Awesome.

**Comment by zischwartz** [comment]
:+1: :+1: This is great

**Comment by SylvainCorlay** [comment]
hop

**Pull request merged**
