### PR TITLE
Merge master into 6.x

### PR DESCRIPTION
**Pull request by jasongrout**
Here's another merge of master into 6.x, following a lot of changes in master over the weekend.

### CODE REVIEW

**Comment by jasongrout** [comment]
@SylvainCorlay helped me merge this since he was responsible for most of the conflicting changes.

**Comment by jdfreder** [comment]
Looks like the python tests are broken by the very last commit

**Comment by jasongrout** [comment]
Hmmm...I'll look into it. Thanks.

**Comment by jasongrout** [comment]
@jdfreder, @SylvainCorlay - I just merged master again into the 6.x branch, and fixed the missing comma that was causing the tests to fail. Do you guys want to take a look? I'd love to move master to point to 6.x :).

**Comment by jasongrout** [comment]
@SylvainCorlay, if you have time to take a look at this - @afshin has been working a lot on the 6.x branch, and I'd love to bring the development back together again so we don't diverge too much.

**Comment by SylvainCorlay** [comment]
I am publishing 5.0.1 today and then separating 5.x from master.

**Pull request merged**
