### PR TITLE
Merge master into 6.x

### PR DESCRIPTION
**Pull request by jasongrout**
Here is an attempt to merge current master (ef5b218) into 6.x (cfb6d1e).

### CODE REVIEW

**Comment by jdfreder** [comment]
Wow, awesome!  This is a nice :gift: to wake up to !  Should we merge this and then we can open another immediately before transitioning master->5.x 6.x->master?

**Comment by jasongrout** [comment]
I think we should merge if it looks good to you. I haven't tested it really, just went carefully through merge conflicts and did what I thought should be done.

**Comment by jasongrout** [comment]
(I'm in a position now where I need changes to both master and the 6.x branch in the jupyterlab widgets, which led to this merge... :).

**Comment by jdfreder** [comment]
We will need another one of these when 5.0 is released.

**Comment by jasongrout** [comment]
Where's the fireworks and cake? :smile:

**Comment by jasongrout** [comment]
actually, :fireworks: and :cake: to you for merging!

**Comment by jdfreder** [comment]
Thanks ^.^

**Comment by minrk** [comment]
🍥s all around.

**Comment by jdfreder** [comment]
Dude, fish cakes, my favorite

**Pull request merged**
