### PR TITLE
Use instances of traits instead of trait classes

### PR DESCRIPTION
**Pull request by jasongrout**
See ipython/traitlets#51

### CODE REVIEW

**Comment by jasongrout** [comment]
I'm not convinced this is a real error.  I don't see a traceback, just a timeout.  Can someone kick this (or show me how to kick it, since I have permissions to this repo now)?

**Comment by minrk** [comment]
Even if the failure is real, it's likely not due to this PR. Will check locally.

**Comment by jdfreder** [comment]
@jasongrout you should be able to kick it yourself.  All you have to do is authenticate using your GitHub with Travis.  Then a restart icon will appear in the top right that you can click.

**Comment by jdfreder** [comment]
The last PR that was merged was passing the tests - https://github.com/ipython/ipywidgets/pull/93 .  Something must have changed elsewhere in the IPython/Jupyter world that's causing this to break..

**Comment by jasongrout** [comment]
I'm testing Travis by reverting my changes, so that this PR is the same as master.

**Comment by jdfreder** [comment]
My guess is it will fail, see my PR that changes the README #97

**Comment by jasongrout** [comment]
Yep, it did.

**Comment by jasongrout** [comment]
I deleted my revert, so now this PR is back to the original commit.  I tested it manually with the intrange slider.  I'm fine with merging this (but as a matter of policy, I shouldn't merge it :).

**Comment by jdfreder** [comment]
Looks to me like the widget JS isn't getting loaded.

**Comment by jdfreder** [comment]
Ah yes, I think it's because https://github.com/jupyter/notebook/pull/120 hasn't been merged.  Although.. it's concerning that #93 passed.

**Pull request merged**
