### PR TITLE
Fix selection

### PR DESCRIPTION
**Pull request by dwillmer**
Fixes:

- [x] Incorrect class attribute name python-side for SelectionSlider.
- [x] Incorrect API for tagging `sync=True` for SelectionSlider.
- [x] Incorrect class attribute name python-side for RadioButtons.
- [x] Actually hook up slide change notification javascript-side for SelectionSlider.
- [x] Use strict equality + cleanup check.

With these fixes, the SelectionSlider readout value actually changes when the slider is moved (this doesn't work on master):

selection

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
LGTM

**Comment by SylvainCorlay** [comment]
Thanks

**Comment by SylvainCorlay** [comment]
:+1: for the eggs example :)

**Comment by dwillmer** [comment]
Merci beaucoup :)

**Comment by jdfreder** [comment]
Thanks @dwillmer !

**Comment by jasongrout** [comment]
> With these fixes, the SelectionSlider readout value actually changes when the slider is moved (this doesn't work on master):

For some reason, this is still broken on the 6.x branch, even those these changes are integrated in. I'll open an issue to keep track of this.

**Pull request merged**
