### PR TITLE
Interact options

### PR DESCRIPTION
**Pull request by jdemeyer**
Implement #430:
```
@interact.option(manual=True)
def function(...):
      pass
```

### CODE REVIEW

**Comment by jdemeyer** [comment]
No idea why Travis CI is failing here. It seems to be complaining about Javascript-related issues while I didn't make any changes to that.

**Comment by SylvainCorlay** [comment]
kicked the build

**Comment by SylvainCorlay** [comment]
Leaving this open to give @carreau the opportunity to comment.

**Comment by jdemeyer** [comment]
Let me just remind that only the last 2 commits need to be reviewed (the first commits are from #762).

**Comment by SylvainCorlay** [comment]
@jdemeyer if you rebase, we should only see those commits.

**Comment by jdemeyer** [comment]
> if you rebase, we should only see those commits.

`<rant>`
I consider that a GitHub bug/misfeature since those first commits are literally (with the same hash) in `master` now, so it shouldn't show them in the diff.

This is IMHO yet another thing that Trac gets right but GitHub does not.
`</rant>`

Anyway, should I rebase or merge in `master` or just leave it?

**Comment by SylvainCorlay** [comment]
I completely agree. I am out for lunch and my desktop computer has 2 ongoing 3-pane merge windows open. I am constantly in the middle of a rebase.

Meld is my ide :)

But I prefer rebase over merge and here the rebase would not require any manual action...

**Comment by jdemeyer** [comment]
Done.

**Comment by Carreau** [comment]
I'm happy with that, I'll trust Sylvain on it, haven't touched widgets in a while.

**Comment by minrk** [comment]
Nice!

**Comment by jasongrout** [comment]
Noting for future people: one huge issue with this implementation is that it can't be used as a decorator anymore:
```python
from ipywidgets import interact
@interact.options(manual=True)(x=(0,10))
def f(x):
    print(x)
```
gives a syntax error. That's because decorators are syntactically limited to a single function call. A way around it is to store the partial interact as another variable:

```python
from ipywidgets import interact
myinteract = interact.options(manual=True)
@myinteract(x=(0,10))
def f(x):
    print(x)
```
(for convenience, an ipywidgets.interact_manual is defined with this option.)

**Pull request merged**
