### PR TITLE
Migrating to typescript

### PR DESCRIPTION
**Pull request by jasongrout**
This PR migrates many of the widgets to use typescript. We also start using a phosphor widget under the hood to provide the dom element. This will allow us in the future to use the phosphor event system to get good resize events, etc.

I also found and fixed several bugs from the typing (like the listen functions don't take a context).

Still todo: 
- [ ] testing framework
- [ ] check to make sure it works on the current notebook still
- [ ] make sure bqplot, pythreejs, ipyleaflet still work, as sanity checks for custom widgets.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Would you be ok walking me through the changes over a call. Since the ts + internal changes in the files makes it difficult to review, I would prefer not having too much changes accumulating on the top of this one...

**Comment by jasongrout** [comment]
Definitely. We can do this today, or I can keep working on changes...

**Comment by jasongrout** [comment]
and I'm also happy to rebase anything to make it easier to review. I realize it's quite a patch dump.

**Comment by blink1073** [comment]
Will be nice when we don't have thousands of lines of `.d.ts` files checked in...

**Comment by lbustelo** [comment]
declarativewidgets builds on top of the WidgetModel, so I'm assuming that this should not affect us. Thoughts?

**Comment by jasongrout** [comment]
It *should* be backwards compatible, so hopefully it won't affect you, @lbustelo. We'll watch this closely, though.

**Comment by jasongrout** [comment]
Another bug bites the dust! https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_int.js#L83 - the w3 spec says the things that you can set this to are *strings* `"true"`, `"false"`, or `"inherit"` (https://www.w3.org/TR/2012/WD-html5-20121025/editing.html#attr-contenteditable), otherwise a syntax error should be thrown. Typescript typing caught this.

**Comment by jasongrout** [comment]
Another one bites the dust! https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_int.js#L566 should also be a string (see https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSPrimitiveValue).

**Comment by jasongrout** [comment]
Here's a serious bug that typing complained about: https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_int.js#L448

**Comment by jasongrout** [comment]
Another one bites the dust! https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_string.js#L105 (calls the method with undefined, but the method will throw an error because of this)

**Comment by jasongrout** [comment]
Typing makes another bug bite the dust! https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_string.js#L98 - setAttribute's value should be a string (see https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-F68F082)

**Comment by jasongrout** [comment]
Typing catches another bug! https://github.com/ipython/ipywidgets/blob/d3dc17843435539e8030d08197627c858d853223/jupyter-js-widgets/src/widget_selectioncontainer.js#L158 - textContent is a function on a jquery element. For an html element, it is an attribute that is set.

**Comment by SylvainCorlay** [comment]
It would make it easier to review without the renaming to typescript. Is the `.ts` extension required?

**Comment by jasongrout** [comment]
> It would make it easier to review without the renaming to typescript. Is the .ts extension required?

That's part of the reason I renamed the files first, and then made the changes to actually convert them to typescript.

But git is also smart about this: `git difftool -t meld --find-renames=10% master` is your friend!

**Comment by jasongrout** [comment]
Another bug! In https://github.com/ipython/ipywidgets/blob/d3dc17843435539e8030d08197627c858d853223/jupyter-js-widgets/src/widget_selection.js#L751, the options parameter is shadowed by the variable created a few lines into the function.

**Comment by jasongrout** [comment]
Still todo: 
- [ ] testing framework
- [ ] check to make sure it works on the current notebook still
- make sure bqplot, pythreejs, ipyleaflet still work, as sanity checks for custom widgets.

**Comment by SylvainCorlay** [comment]
This PR fixes #14.

**Comment by jasongrout** [comment]
Several more bugs! (several styling bugs, but these weren't caught by typing, but instead by going through all of the examples)

**Comment by jasongrout** [comment]
@SylvainCorlay - tests pass for me, but it appears that travis has errors. Do tests pass for you?

**Comment by SylvainCorlay** [comment]
Merging after in-person review and discussion with Jason, so that we can iterate. We are aware of the testing issue.

**Pull request merged**
