### PR TITLE
Document __manual

### PR DESCRIPTION
**Pull request by jdfreder**
@denfromufa @SylvainCorlay

### CODE REVIEW

**Comment by denfromufa** [comment]
@jdfreder the metadata shows python 2.7, but not all syntax is valid for it in this notebook: print and function annotations.

**Comment by denfromufa** [comment]
also this pull slightly conflicts: https://github.com/ipython/ipywidgets/pull/292

**Comment by jdfreder** [comment]
> @jdfreder the metadata shows python 2.7, but not all syntax is valid for it in this notebook: print and function annotations.

Thanks, fixed

**Comment by jdfreder** [comment]
@denfromufa I merged #292 into this

**Comment by denfromufa** [comment]
Thanks a lot! Now I can go forward with my nested widgets to emulate
simplified polestar using pandas!

**Pull request merged**
