### PR TITLE
Make long description part of setup.py

### PR DESCRIPTION
**Pull request by SylvainCorlay**
So that we can add templating in the long description.
@minrk

### CODE REVIEW

**Comment by jdfreder** [comment]
This gets picked up by PyPI ?

**Comment by jdfreder** [comment]
- just read @minrk 's comments on the other PR, answered my question.

**Comment by SylvainCorlay** [comment]
I think it would, but it is difficult to check without a release...

**Comment by jasongrout** [comment]
This sort of thing gets picked up in my pythreejs library: https://github.com/jovyan/pythreejs/blob/master/setup.py#L8

See the PyPi page: https://pypi.python.org/pypi/pythreejs/

**Comment by minrk** [comment]
@jdfreder thanks. If it gets long enough that people would prefer to have .rst highlighting on it, a `pypi_description.rst` that gets read in setup.py would be fine, too.

**Pull request merged**
