### PR TITLE
Move jupyter-js-widgets PRs out of master and into 6.x branch

### PR DESCRIPTION
**Pull request by afshin**
- [x] fix bug: travis build not working; turns out it's been using an old version of `node` all along but since the build worked, nobody noticed (https://github.com/ipython/ipywidgets/pull/457/commits/6d5eb8d6119c62ea3f3853779d117186047c754f)
- [x] fix bug: `IntSlider` not rendering (https://github.com/ipython/ipywidgets/pull/457/commits/0b0c64fb276b8f492cd153b9436e56263ba80efe)
- [x] add: new implementation of `TabView` that does not use Bootstrap or jQuery. It uses the phosphor `TabBar` (https://github.com/ipython/ipywidgets/pull/457/commits/9f9c826d9afab592bd06dac1ac3c6e5f49b30adf, https://github.com/ipython/ipywidgets/pull/457/commits/3fb4536bf6d39f68c62dc2191a3f907cdad1f4a2, https://github.com/ipython/ipywidgets/pull/457/commits/0997bb34148823c5b29b7ed8213b9938a07de41f, https://github.com/ipython/ipywidgets/pull/457/commits/54b5702e81ff99f23035fbc629f39a27a9b02041)
- [x] add: new button styles (https://github.com/ipython/ipywidgets/pull/457/commits/93bb594054ee2bdadeb4b4df6807d26ccd333b29)

cc: @jdfreder @SylvainCorlay @jasongrout @dwillmer

### CODE REVIEW

**Comment by dwillmer** [comment]
LGTM

**Comment by sccolbert** [comment]
Howdy folks. Can someone please hit the green button before this becomes stale?

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by sccolbert** [comment]
:tada:

**Comment by jasongrout** [comment]
Thanks Sylvain! And thanks Darian for the PR!

**Comment by afshin** [comment]
🎆 

Awesome, thanks!

**Comment by jdfreder** [comment]
> Howdy folks. Can someone please hit the green button before this becomes stale?

 :umbrella: I predict the merge of the 6.x branch into master as not being straightforward.  The two have already diverged in a few places.

**Pull request merged**
