### PR TITLE
Add `continuous_update` flag to the sliders,

### LINKED ISSUE #160: option to transmit slider value on release, rather than on drag
The code at https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/widget_int.js#L176 executes the slider change handler anytime the slider is dragged, while it is being dragged.  Often a calculation takes so much time that it's better to only update when the slider is released.  It would be great to have an option to the slider so that it updates only on mouse release, rather than mouse drag.

Thanks to @suhr for bringing this up on gitter

### PR DESCRIPTION
**Pull request by jdfreder**
This adds a `continuous_update` flag to the int and float range/single sliders. The flag allows you to set whether or not the sliders update as they are being dragged.

Example:
```python
from ipywidgets import *
from IPython.display import display
i = IntSlider(continuous_update=False)
display(i)

def handle(key, value):
    print value
i.on_trait_change(handle, 'value')
```

Drag the slider, observe that the readout changes, but the value doesn't print until released.

closes #160

### CODE REVIEW

**Comment by jdfreder** [comment]
@SylvainCorlay this is ready for review

Action shot: 

demo

**Comment by blink1073** [comment]
noice

**Comment by jdfreder** [comment]
Haha love the pic @blink1073

**Comment by ellisonbg** [comment]
Love it. Wondering if there is a better name than `continuous_update`? Because, you know, naming things is so much fun I want to prolong it...

**Comment by SylvainCorlay** [comment]
there could be an enum trait attribute `update` of values `['on_slide', 'on_stop']`...

**Comment by SylvainCorlay** [comment]
I am good with this one, if everyone agrees on the naming.

**Comment by jdfreder** [comment]
`update_on_slide` ?

**Comment by jdfreder** [comment]
> There could be an enum trait attribute

We could do that too; however, I think a flag is easier since it's only two values.

**Comment by SylvainCorlay** [comment]
@ellisonbg merge?

**Comment by ellisonbg** [comment]
I haven't figured out any other better names. Let's go with the current state of the PR.

**Pull request merged**
