### PR TITLE
jupyterlab@^0.11.0

### PR DESCRIPTION
**Pull request by gnestor**
labextension breaks when running jupyterlab@^0.11

### CODE REVIEW

**Comment by jasongrout** [comment]
Should we change it to `~0.10.0` then?

**Comment by gnestor** [comment]
From my undestanding, `~0.10.0 := >=0.10.0 <0.11.0` whereas `~0 := >=0.0.0 <1.0.0`

https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1

**Comment by jasongrout** [comment]
Aren't we targeting `>=0.10.0 <0.11.0`?

**Comment by gnestor** [comment]
The purpose of this commit is to make interop between ipywidgets and jupyterlab more flexible by allowing higher minor versions, because currently I'm running jupyterlab 0.11.2 and ipywidgets depends on ^0.10.0.

**Comment by blink1073** [comment]
The two are not rectifiable, because 0.10 -> 0.11 is considered a major version release.  The solution is for ipywidgets to bump to 0.11, especially because 0.10 has known issues with state restoration.

**Comment by gnestor** [comment]
Ok, I see. I'll update the commit...

**Comment by jasongrout** [comment]
> The two are not rectifiable, because 0.10 -> 0.11 is considered a major version release. The solution is for ipywidgets to bump to 0.11, especially because 0.10 has known issues with state restoration.

Agreed. Grant, can you make sure it works in 0.11.0? I haven't had time to check things yet.

**Comment by gnestor** [comment]
I tested and Widget List.ipynb is rendering with no issues.

**Comment by ivanov** [comment]
I'm going to go for and merge this. After all, "laugh in the face of danger" is the official jupyter motto, is it not? 

Happy hacking! :bowtie:

**Pull request merged**
