### PR TITLE
WIP More jquery removal

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@afshin this and #776 were leftover from the jquery removal. I am not sure what the `collapse` was supposed to do.

**Comment by afshin** [comment]
Collapsing is just for accordions, I think. Good eye catching those jQuery methods.

**Comment by SylvainCorlay** [comment]
I just wonder how this even works, unless bootstrap does voodoo with the css selectors that we are using. `page.collapse` is only used when updating from the backend or another view.

**Comment by afshin** [comment]
Yeah, you're right, I can't tell where that class name comes from, either.

**Comment by jasongrout** [comment]
This is superseded by #837.

**Comment by jasongrout** [comment]
And it was bootstrap - took me a while to realize it wasn't actually magic.

**Pull request closed without merging**
