### PR TITLE
Issue 544 bugfixes

### PR DESCRIPTION
**Pull request by afshin**
These are bugfixes for https://github.com/ipython/ipywidgets/issues/544

- [x] Color picker widget respects widget width
- [x] Dropdown widget respects widget width
- [x] Progress bar widget renders `'vertical'` mode correctly
- [x] Fix Dropdown widget `keydown` handler inside notebook

cc: @jasongrout @SylvainCorlay

### CODE REVIEW

**Comment by afshin** [comment]
screen shot 2016-05-03 at 7 24 19 pm

**Comment by afshin** [comment]
FYI, I added the `.fa` class back in for button icons.

screen shot 2016-05-03 at 9 03 21 pm

**Comment by jasongrout** [comment]
Darian, those changes look good; thanks. One more thing about the dropdown - if the size of the dropdown has changed, the actual dropdown list no longer matches the width of the control (see the image below - the grey box is a different width than the control). Can we get the list to match the width of the control?

screen shot 2016-05-03 at 5 05 31 pm

**Comment by afshin** [comment]
@jasongrout Good call, the drop list width needs to be calculated at run-tim in JS (it used to just be a static 300px).

**Comment by jasongrout** [comment]
Nice, thanks! I also investigated a bit more deeply what the `<select>` behavior is on different platforms over in #562. No conclusions there, but there is precedence for having the dropdown list box width be more than the dropdown control size.

**Pull request merged**
