### PR TITLE
Some changes to be able to run examples

### PR DESCRIPTION
**Pull request by lbustelo**
Basically using `npm link`

The only bad thing is that the dependency to ipywidgets is not explicit  in the examples json. I only did web3.

### CODE REVIEW

**Comment by lbustelo** [comment]
info about `npm link` https://docs.npmjs.com/cli/link

**Comment by SylvainCorlay** [comment]
Why renaming the npm package to ipywidgets?

**Comment by lbustelo** [comment]
Cause when doing the npm link it used the name in package.json. Since in code you guys do require('ipywidgets'), that was the easiest thing to change n

**Comment by SylvainCorlay** [comment]
Ah, I see the remaining `require("ipywidget")` in web3, but it should be changed into
require("jupyter-js-widgets"), which will be the name on npm.

**Comment by SylvainCorlay** [comment]
@lbustelo I opened #268 fixing the naming issue and checked that web3 works.

**Comment by lbustelo** [comment]
After much trial and error... my issues were resolved by upgrading `npm`. I'm now at `3.5.2` and it worked. Previously I was running `2.7.4`,

**Comment by jdfreder** [comment]
Thanks @lbustelo !  Sorry for the pain this caused :(

**Comment by lbustelo** [comment]
no problem. Good excuse to dig around and learn

**Pull request closed without merging**
