### PR TITLE
Add the ability to change the readout logic for sliders easily.

### LINKED ISSUE #172: Setting IntRangeSlider readout to pick elements from an array-like object.
I've seen a few widget applications using the IntRangeSlider as a date selector, for example. It would be cool if the readout display values could be set dynamically.

### PR DESCRIPTION
**Pull request by jdfreder**
With this PR you can change the readout logic by overriding the new `valueToString` and `stringToValue` methods in Javascript.

closes #172

### CODE REVIEW

**Comment by jdfreder** [comment]
Broken, do not merge yet

**Comment by jdfreder** [comment]
Ok this is working now. @SylvainCorlay

**Comment by SylvainCorlay** [comment]
@jdfreder can you explain a bit what this does?

**Comment by jdfreder** [comment]
@jgoad desired the ability to change the readout format from numbers to dates.  Specifically he wants to use the IntRangeSlider to allow the user to select a range of dates.  This requires him to subclass the JS which is fine; however, the readout logic is tightly coupled to the other properties of the widgets, so he'd have to re-implement a lot of functionality he shouldn't have to.  This PR just decouples the readout parsing and formatting code, so it can be easily replaced.

**Comment by SylvainCorlay** [comment]
This is related to the Date trait type work then.

**Pull request merged**
