### PR TITLE
WIP Jupyterlab-style and css variable-based styling for ipywidgets

### PR DESCRIPTION
**Pull request by SylvainCorlay**
~~This works with the current *master* of jupyterlab. (Last release is 0.5.1)~~ jupyterlab 0.6.0

### CODE REVIEW

**Comment by gnestor** [comment]
I tested and everything looks fine. Is this ready to merge?

**Comment by SylvainCorlay** [comment]
Thanks for testing!

This is not ready (it only applies to the jupyterlab case for now).

**Comment by SylvainCorlay** [comment]
Reviewed in person with @jasongrout, who is re-aplying the changes for the upgrade to jupyterlab 0.6.0.

Once this gets in and we  can push the two other changes we discussed w.r.t. vertical alignment and publish a 6.0 beta for Fernando.

**Comment by jasongrout** [comment]
Superseded by #855. Sylvain, the problem with the sliders had to do with a change I made in refactoring the lab plugin - the css files were moved to plugin.ts instead of index.ts.

**Comment by jasongrout** [comment]
Sorry, I forgot you gave me write access to your repo so we could just collaborate on this branch.

**Comment by SylvainCorlay** [comment]
> Sorry, I forgot you gave me write access to your repo so we could just collaborate on this branch.

I did invite you to my fork but you did not accept yet.

Anyways, I am fine with your changes, will merge your fork.

**Pull request closed without merging**
