### PR TITLE
Widths

### PR DESCRIPTION
**Pull request by jasongrout**
Many widgets (such as text, select, slider, etc.) now let you set the width with `widget.layout.width`.

This does not fix the multiple select, which needs to be overhauled.

This is a partial fix to #1073.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
lgtm

**Comment by SylvainCorlay** [comment]
@jasongrout can hop on gitter?

**Comment by jasongrout** [comment]
This may change the widths of widgets in a layout, but tries to make it even more consistent by making the width just depend on the outermost container's width.

**Comment by jasongrout** [comment]
It looks like since the default value for flex-shrink is 1, if the widgets would overflow the output area, they do shrink until they fit. However, if they do fit, they are the 'correct' widths and lay out nicely.

**Comment by jasongrout** [comment]
#1081 continues this.

**Pull request merged**
