### PR TITLE
Revert dropdown control to use a native select control.

### PR DESCRIPTION
**Pull request by jasongrout**
Currently there are serious keyboard handling problems with the dropdown control (see https://github.com/ipython/ipywidgets/issues/1049), and a lack of documentation for how the control behaves (see https://github.com/ipython/ipywidgets/issues/1055). We revert to the native select control until we rectify both of these issues and split the UI control off to be a phosphor control which the widget wraps.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @SylvainCorlay, @ellisonbg

**Comment by ellisonbg** [comment]
OK, but the plan is to still implement a phosphor widget version of the dropdown?

**Comment by jasongrout** [comment]
Yes. I think we need a good spec (see #1055 for a start) before moving ahead, and this temporarily fixes the problem in #1049 that makes the notebook pretty unusable right now.

**Comment by jasongrout** [comment]
> OK, but the plan is to still implement a phosphor widget version of the dropdown?

That's why I left the current code/CSS in there - to be refactored out.

**Pull request merged**
