### PR TITLE
PR #725 broke the fixed() functionality of @interact. This fixes it.

### PR DESCRIPTION
**Pull request by jasongrout**
See #725.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @jdemeyer, @SylvainCorlay.

**Comment by jdemeyer** [comment]
If something is undocumented and untested, it's not surprising that it breaks. I would suggest that you add a testcase.

**Comment by jdemeyer** [comment]
Speaking of `fixed`, I don't really understand why it's not just a widget. This `fixed` class looks like an ugly hack that somebody once added.

**Comment by jasongrout** [comment]
> If something is undocumented and untested, it's not surprising that it breaks. I would suggest that you add a testcase.

Point taken. I noticed it because the Image Processing example notebook broke (which is sort of a manual test case :).

**Comment by jasongrout** [comment]
> Speaking of fixed, I don't really understand why it's not just a widget. This fixed class looks like an ugly hack that somebody once added.

It's sort of the python half of a widget, which is all that is needed here since it is just maintaining the value in the kernel.

I'm certainly open to introducing currying or partial functions in a different way. Perhaps we could just rewrite the examples to use `functools.partial`.

**Comment by jasongrout** [comment]
> This fixed class looks like an ugly hack that somebody once added.

I just talked to @ellisonbg, who I think implemented it originally, and it appears it was a concession to simplify things for beginners.

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by minrk** [comment]
I'm in favor of using and encouraging and documenting `functools.partial` over `fixed`. I think we can keep `fixed` for those who aren't comfortable with currying without any real downside. A test for exercise would definitely be good, though.

**Pull request merged**
