### PR TITLE
Vertical progress bar

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Adding an `orientation` attribute to the `FloatProgress` and `IntProgress` widgets.

### CODE REVIEW

**Comment by jdfreder** [comment]
This PR doesn't work for me.  After comparing against master, not forgetting to run `gulp css` and dump my cache, I realized that it's the contents here.  Although I wasn't quite sure why, the correct CSS isn't being applied.

**Comment by SylvainCorlay** [comment]
Weird, I did check that everything works ok for me, recompiling the css to the master branch and back to this, with multiple browsers.

**Comment by jdfreder** [comment]
I'll verify that all of my other repos are on master, and try again.

**Comment by jdfreder** [comment]
Ah, I had two ipywidgets copies.  Deleted the other, and its conflicting files, and everything works.

**Pull request merged**
