### PR TITLE
Fixes to Accordion widget

### PR DESCRIPTION
**Pull request by mwcraig**
There are a couple of issues that come up if you try nesting accordion widgets:

+ The title of an accordion widget panel containing an accordion widget gets applied to all panels of that sub-accordion widget.
+ When an accordion widget panel containing an accordion widget gets opened, all panels of the sub-accordion widget also get opened.

This PR fixes those issues and checks with an index is in range before trying to close it when the `selected_index` is updated. That silences a couple of javascript errors that otherwise occur if you set `selected_index=-1` when you create the widget start the widget with all panels closed.

I wasn't sure how to test this sort of thing so no tests are included....happy to add them if you want.

I'll add a couple screenshots in a moment and a link to a sample notebook that demonstrates the problem.

### CODE REVIEW

**Comment by mwcraig** [comment]
A sample notebook that creates a nested accordion is at https://gist.github.com/mwcraig/7f023456fa391562b611

**Comment by mwcraig** [comment]
## Screen capture before fix:

short-accordion-bad

**Comment by mwcraig** [comment]
## Screen capture after fix

short-accordion-good

**Comment by jdfreder** [comment]
Thanks @mwcraig !  This is great!

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by jasongrout** [comment]
Yes, +1

**Comment by jasongrout** [comment]
Thanks also for the comprehensive screenshots.  It made it really easy to see exactly what you were saying and see why your changes fixed the issue.

**Comment by mwcraig** [comment]
Thanks for merging this so quickly! I had no idea how to explain the issue without screenshots :)

**Pull request merged**
