### PR TITLE
6.x

### PR DESCRIPTION
**Pull request by SylvainCorlay**
@jdfreder @jasongrout @afshin this is the PR merging 6.x into the new master since we now have a separate 5.x branch.

### CODE REVIEW

**Comment by jasongrout** [comment]
I just merged master into 6.x and pushed here to fix the merge conflicts.

**Comment by jasongrout** [comment]
@SylvainCorlay - that button is green now :)

**Comment by jasongrout** [comment]
Yeah! 6.x, here we come! @afshin @dwillmer

**Comment by afshin** [comment]
🎆

**Comment by SylvainCorlay** [comment]
Yeah!

**Comment by dwillmer** [comment]
👍

**Pull request merged**
